import { assessReadiness, calculateQuality, escapeHtml as e, portfolioMetrics, priorityScore, statusClass, USE_CASES, validateAsset } from './engine.mjs';

const DISPLAY = {
  Draft:'Utkast', Review:'Til vurdering', Approved:'Godkjent', Published:'Publisert',
  Open:'Åpen', 'In progress':'Pågår', Done:'Ferdig',
  Ready:'Klar', 'Ready with controls':'Klar med tiltak', 'Not ready':'Ikke klar',
  Pass:'Bestått', 'Control required':'Krever tiltak', Blocker:'Sperre',
  High:'Høy', Medium:'Middels', Low:'Lav',
  Public:'Offentlig', Internal:'Intern', Confidential:'Konfidensiell'
};
const TYPES = {
  Dataset:'Datasett', 'Data service/API':'Datatjeneste / API', 'Document collection':'Dokumentsamling',
  'Information model':'Informasjonsmodell', 'Business term':'Virksomhetsbegrep', 'Code list':'Kodeverk',
  'Report/analytical product':'Rapport / analyseprodukt'
};
const display = value => DISPLAY[value] || value;
const typeLabel = value => TYPES[value] || value;
const badge = value => `<span class="status status-${statusClass(value)}">${e(display(value))}</span>`;
const head = (kicker,title,copy,actions='') => `<header class="page-header"><div><p class="eyebrow">${e(kicker)}</p><h1>${e(title)}</h1><p>${e(copy)}</p></div><div class="page-actions">${actions}</div></header>`;
const metric = (label,value,note,tone='neutral') => `<article class="metric metric-${tone}"><span>${e(label)}</span><strong>${e(value)}</strong><small>${e(note)}</small></article>`;
const typeIcon = type => ({Dataset:'▥','Data service/API':'⇄','Document collection':'▤','Information model':'◇','Business term':'Aa','Code list':'#','Report/analytical product':'▦'}[type]||'•');
const field = (label,value) => `<div class="meta-row"><dt>${e(label)}</dt><dd>${value?e(display(value)):'<span class="missing">Ikke registrert</span>'}</dd></div>`;

export function overview({state,assets,relationships}) {
  const m=portfolioMetrics(assets,relationships);
  const rows=assets.map(asset=>({asset,findings:validateAsset(asset,assets,relationships),assessment:assessReadiness(asset,asset.type==='Report/analytical product'?'analytical_reporting':'enterprise_search')}))
    .sort((a,b)=>b.findings.filter(f=>f.severity==='required').length-a.findings.filter(f=>f.severity==='required').length).slice(0,6);
  return `${head('Styringsoversikt','Tillit før automatisering','Her ser du hva som er ryddig, hva som mangler, og hvilke oppgaver som bør tas først.','<button class="button primary" data-action="open-register">Registrer ressurs</button>')}
  <section class="hero"><div><span>Syntetisk eksempel · CivicWorks</span><h2>Se på informasjonsgrunnlaget før du kobler på mer automatisering.</h2><p>MetaReady samler eierskap, metadata, proveniens, tilgang, livsløp, kvalitet og AI-beredskap i samme arbeidsflate.</p><div><button class="button primary" data-action="inspect" data-id="CW-DOC-002">Se på svak ressurs</button><button class="button ghost" data-view="readiness">Kjør AI-vurdering</button></div></div><dl><div><dt>${m.assets}</dt><dd>ressurser</dd></div><div><dt>${m.relationships}</dt><dd>relasjoner</dd></div><div><dt>12</dt><dd>profilregler</dd></div><div><dt>0</dt><dd>API-nøkler</dd></div></dl></section>
  <section class="metrics">${metric('Informasjonsressurser',m.assets,`${m.published} publisert`)}${metric('Eierskapshull',m.ownershipGaps,'Mangler tydelig ansvar',m.ownershipGaps?'warning':'good')}${metric('Åpne profilkrav',m.criticalFindings,'Krav som må følges opp',m.criticalFindings?'danger':'good')}${metric('Klar eller klar med tiltak',m.ready+m.readyWithControls,`${m.notReady} ikke klar`,m.notReady?'warning':'good')}</section>
  <section class="panel"><div class="panel-head"><div><p class="eyebrow">Prioritering</p><h2>Største styringshull</h2></div><button class="text-button" data-view="catalog">Åpne katalogen →</button></div><div class="table-wrap"><table><thead><tr><th>Ressurs</th><th>Status</th><th>Åpne krav</th><th>AI-vurdering</th><th></th></tr></thead><tbody>${rows.map(({asset,findings,assessment})=>`<tr><td><button class="table-link" data-action="inspect" data-id="${asset.id}">${e(asset.title)}</button><small>${e(typeLabel(asset.type))}</small></td><td>${badge(asset.status)}</td><td><strong>${findings.filter(f=>f.severity==='required').length}</strong></td><td>${badge(assessment.status)}</td><td><button class="icon-button" aria-label="Åpne ${e(asset.title)}" data-action="inspect" data-id="${asset.id}">→</button></td></tr>`).join('')}</tbody></table></div></section>`;
}

export function catalog({state,assets,relationships,can}) {
  const f=state.catalogFilters;
  const shown=assets.filter(a=>(!f.query||`${a.title} ${a.id} ${a.type} ${a.unit}`.toLowerCase().includes(f.query.toLowerCase()))&&(!f.type||a.type===f.type)&&(!f.status||a.status===f.status)&&(!f.ownerGap||!a.owner||!a.steward));
  const asset=assets.find(a=>a.id===state.selectedAssetId)||shown[0]||assets[0];
  const findings=validateAsset(asset,assets,relationships);
  const quality=calculateQuality(asset,findings);
  const types=[...new Set(assets.map(a=>a.type))];
  const statusOptions=['Draft','Review','Approved','Published'];
  return `${head('Informasjonskatalog','Finn, forstå og forbedre informasjonsressurser','Søk på tvers av dokumenter, data, modeller, begreper, kodeverk, API-er og rapporter.','<button class="button primary" data-action="open-register">Registrer ressurs</button>')}
  <section class="filters"><label><span>Søk</span><input id="catalog-query" value="${e(f.query)}" placeholder="Tittel, ID, type eller enhet"></label><label><span>Type</span><select id="catalog-type"><option value="">Alle</option>${types.map(v=>`<option value="${e(v)}" ${v===f.type?'selected':''}>${e(typeLabel(v))}</option>`).join('')}</select></label><label><span>Status</span><select id="catalog-status"><option value="">Alle</option>${statusOptions.map(v=>`<option value="${v}" ${v===f.status?'selected':''}>${display(v)}</option>`).join('')}</select></label><label class="check"><input id="catalog-owner-gap" type="checkbox" ${f.ownerGap?'checked':''}><span>Kun eierskapshull</span></label><span class="result-count">${shown.length} treff</span></section>
  <div class="catalog-layout"><section class="panel catalog-list"><div class="table-wrap"><table><thead><tr><th>Ressurs</th><th>Type</th><th>Eier</th><th>Status</th><th>Krav</th></tr></thead><tbody>${shown.map(a=>{const n=validateAsset(a,assets,relationships).filter(x=>x.severity==='required').length;return `<tr class="${a.id===asset.id?'selected':''}" data-action="select" data-id="${a.id}" tabindex="0"><td><strong>${e(a.title)}</strong><small>${e(a.id)} · v${e(a.version)}</small></td><td><span class="type"><b>${typeIcon(a.type)}</b>${e(typeLabel(a.type))}</span></td><td>${a.owner?e(a.owner):'<span class="missing">Mangler</span>'}</td><td>${badge(a.status)}</td><td><span class="count ${n?'bad':''}">${n}</span></td></tr>`}).join('')||'<tr><td colspan="5">Ingen treff. Endre filtrene.</td></tr>'}</tbody></table></div></section>
  <aside class="panel inspector"><div class="asset-title"><span class="type-icon">${typeIcon(asset.type)}</span><div><small>${e(asset.id)} · v${e(asset.version)}</small><h2>${e(asset.title)}</h2>${badge(asset.status)}</div></div><p>${e(asset.description)}</p><dl>${field('Eier',asset.owner)}${field('Forvalter',asset.steward)}${field('Sensitivitet',asset.sensitivity)}${field('Neste revisjon',asset.reviewDate)}${field('Proveniens',asset.provenance)}</dl><div class="quality-mini">${quality.slice(0,5).map(q=>`<div><span>${e(q.label)}</span><i><b style="width:${q.score}%"></b></i><strong>${q.score}</strong></div>`).join('')}</div><div class="finding-summary"><strong>${findings.length} profilfunn</strong><span>${findings.filter(x=>x.severity==='required').length} krav · ${findings.filter(x=>x.severity!=='required').length} anbefalinger</span></div><div class="stack-actions"><button class="button secondary" data-action="detail" data-id="${asset.id}">Åpne diagnose</button><button class="button secondary" data-action="brief" data-id="${asset.id}">Eksporter notat</button></div></aside></div>
  ${state.detailOpen?assetDetail({state,assets,relationships,can,asset}):''}`;
}

function assetDetail({state,assets,relationships,can,asset}) {
  const findings=validateAsset(asset,assets,relationships);
  const quality=calculateQuality(asset,findings);
  const workflowStates=['Draft','Review','Approved','Published'];
  return `<section class="panel detail"><div class="panel-head"><div><p class="eyebrow">Forklarbar diagnose</p><h2>${e(asset.title)}</h2><p>Profil: INTERNAL_ASSET_MINIMUM_V1 · her vises bevis, betydning og foreslått tiltak.</p></div><button class="icon-button" data-action="close-detail" aria-label="Lukk diagnose">×</button></div><div class="workflow"><span>Arbeidsflyt</span>${workflowStates.map(status=>`<button class="${asset.status===status?'active':''}" data-action="workflow" data-next="${status}" data-id="${asset.id}" ${!can('workflow')?'disabled':''}>${display(status)}</button>`).join('')}</div><div class="detail-grid"><div><h3>Åpne funn</h3>${findings.map(f=>`<article class="finding"><div>${badge(f.severity==='required'?'Krav':'Anbefaling')}<code>${f.id}</code></div><h3>${e(f.label)}</h3><p><strong>Bevis:</strong> ${e(f.evidence)}</p><p><strong>Hvorfor:</strong> ${e(f.why)}.</p><p><strong>Tiltak:</strong> ${e(f.fix)}.</p>${f.id!=='META-012'?`<button class="button secondary" data-action="remediate" data-id="${asset.id}" data-rule="${f.id}" ${!can('remediate')?'disabled':''}>Bruk foreslått utbedring</button>`:''}</article>`).join('')||'<div class="empty">Ingen åpne funn under aktiv profil.</div>'}</div><div><h3>Kvalitetsdimensjoner</h3>${quality.map(q=>`<div class="quality"><div><strong>${e(q.label)}</strong><span>${q.score}/100</span></div><i><b style="width:${q.score}%"></b></i><small>${e(q.evidence)}</small></div>`).join('')}</div></div><div class="limitation"><strong>Avgrensning</strong><p>Profilen er et demonstrasjonsminimum. Resultatet er ikke juridisk vurdering eller samsvarssertifisering.</p></div></section>`;
}

export function readiness({state,assets}) {
  const asset=assets.find(a=>a.id===state.readinessAssetId)||assets[1];
  const a=assessReadiness(asset,state.useCaseId);
  const actions=`<button class="button secondary" data-action="brief" data-id="${asset.id}">Eksporter vurdering</button>`;
  return `${head('AI-beredskap','Vurder informasjon for en konkret bruk','Den samme ressursen kan fungere fint for søk og være dårlig egnet for en handlende agent. Derfor vurderes bruksområdene hver for seg.',actions)}
  <section class="controls"><label><span>Ressurs</span><select id="readiness-asset">${assets.map(x=>`<option value="${x.id}" ${x.id===asset.id?'selected':''}>${e(x.title)}</option>`).join('')}</select></label><label><span>Bruksområde</span><select id="use-case">${Object.values(USE_CASES).map(x=>`<option value="${x.id}" ${x.id===a.useCase.id?'selected':''}>${e(x.label)}</option>`).join('')}</select></label><p><strong>${e(a.useCase.label)}</strong><br>${e(a.useCase.description)}</p></section>
  <section class="assessment assessment-${statusClass(a.status)}"><div><strong>${a.score}</strong><span>av 100</span></div><div><p class="eyebrow">Beslutningsstøtte</p><h2>${e(display(a.status))}</h2><p>${a.blockers.length?`${a.blockers.length} sperre(r) krever tiltak.`:'Ingen sperrer er registrert.'}</p></div><button class="button primary" data-action="assessment-backlog" data-id="${asset.id}">Opprett tiltak</button></section>
  <section class="panel"><div class="table-wrap"><table><thead><tr><th>Dimensjon</th><th>Resultat</th><th>Bevis og antakelse</th><th>Anbefalt tiltak</th><th>Ansvar</th></tr></thead><tbody>${a.dimensions.map(d=>`<tr><td><strong>${e(d.label)}</strong><div class="bar"><b style="width:${d.score}%"></b></div><small>${d.score}% · sikkerhet ${e(display(d.confidence))}</small></td><td>${badge(d.result)}</td><td>${e(d.evidence)}<small>Antakelse: ${e(d.assumption)}</small></td><td>${e(d.action)}</td><td>${e(d.accountableRole)}</td></tr>`).join('')}</tbody></table></div></section><section class="limitation"><strong>Viktig avgrensning</strong><p>${e(a.limitation)}</p></section>`;
}

export function lineage({state,assets,relationships}) {
  const asset=assets.find(a=>a.id===state.lineageAssetId)||assets[0];
  const direct=relationships.filter(r=>r.from===asset.id||r.to===asset.id);
  const byId=id=>assets.find(a=>a.id===id);
  const linked=direct.map(r=>({r,a:byId(r.from===asset.id?r.to:r.from)})).filter(x=>x.a);
  const impacted=relationships.filter(r=>r.from===asset.id).map(r=>byId(r.to)).filter(Boolean);
  const actions=`<button class="button secondary" data-action="brief" data-id="${asset.id}">Eksporter konsekvensnotat</button>`;
  return `${head('Linjer og konsekvens','Se opphav, avhengigheter og mulig påvirkning','Relasjonene har bevis og en enkel vurdering av sikkerhet. Grafikken suppleres av en vanlig tabell.',actions)}<section class="controls one"><label><span>Startressurs</span><select id="lineage-asset">${assets.map(x=>`<option value="${x.id}" ${x.id===asset.id?'selected':''}>${e(x.title)}</option>`).join('')}</select></label><p><strong>${direct.length}</strong> direkte relasjoner · <strong>${impacted.length}</strong> direkte nedstrøms påvirket</p></section><div class="lineage-layout"><section class="panel network"><div class="node center"><small>${e(typeLabel(asset.type))}</small><strong>${e(asset.title)}</strong></div>${linked.map(({r,a})=>`<button class="node" data-action="lineage-select" data-id="${a.id}"><small>${e(r.type)} · ${e(display(r.confidence))}</small><strong>${e(a.title)}</strong></button>`).join('')||'<div class="empty">Ingen registrerte relasjoner.</div>'}</section><aside class="panel"><p class="eyebrow">Endringsvurdering</p><h2>Mulig konsekvens</h2><p>Ved en større endring bør berørte eiere få se den før publisering.</p>${impacted.map(a=>`<button class="impact" data-action="lineage-select" data-id="${a.id}"><span>${typeIcon(a.type)}</span><div><strong>${e(a.title)}</strong><small>${e(typeLabel(a.type))}</small></div><b>→</b></button>`).join('')||'<div class="empty">Ingen direkte nedstrøms treff.</div>'}<button class="button secondary full" data-action="record-impact" data-id="${asset.id}">Registrer beslutning</button></aside></div><section class="panel"><h2>Relasjonstabell</h2><div class="table-wrap"><table><thead><tr><th>Fra</th><th>Relasjon</th><th>Til</th><th>Bevis</th><th>Sikkerhet</th></tr></thead><tbody>${direct.map(r=>`<tr><td>${e(byId(r.from)?.title||r.from)}</td><td><strong>${e(r.type)}</strong></td><td>${e(byId(r.to)?.title||r.to)}</td><td>${e(r.evidence)}</td><td>${badge(r.confidence)}</td></tr>`).join('')||'<tr><td colspan="5">Ingen relasjoner.</td></tr>'}</tbody></table></div></section>`;
}

export function backlog({state}) {
  const sorted=[...state.backlog].sort((a,b)=>priorityScore(b)-priorityScore(a));
  const statuses=['Open','In progress','Done'];
  return `${head('Tiltakslogg','Gjør styringshull om til arbeid','Formelen er enkel og synlig: effekt, risiko og hast trekker opp; innsats trekker ned.','<button class="button secondary" data-action="export-backlog">Eksporter CSV</button>')}<section class="formula"><div><p class="eyebrow">Prioriteringsmodell</p><strong>((effekt × 0,38) + (hast × 0,27) + (risikoreduksjon × 0,35)) − innsats</strong></div><div><span><b>${sorted.length}</b> tiltak</span><span><b>${sorted.filter(x=>x.status==='Open').length}</b> åpne</span><span><b>${sorted.filter(x=>priorityScore(x)>=75).length}</b> høy prioritet</span></div></section><section class="panel"><div class="table-wrap"><table><thead><tr><th>Prioritet</th><th>Tiltak</th><th>Ressurs</th><th>Ansvar</th><th>Status</th></tr></thead><tbody>${sorted.map(item=>`<tr><td><span class="priority ${priorityScore(item)>=75?'high':priorityScore(item)>=55?'medium':''}">${priorityScore(item)}</span></td><td><strong>${e(item.title)}</strong><p>${e(item.reason)}</p><small>Effekt ${item.impact} · risiko ${item.riskReduction??item.risk} · hast ${item.urgency} · innsats ${item.effort}</small></td><td>${item.assetIds.map(id=>`<code>${e(id)}</code>`).join(' ')}</td><td>${e(item.ownerRole)}</td><td><select data-action="backlog-status" data-id="${item.id}">${statuses.map(v=>`<option value="${v}" ${v===item.status?'selected':''}>${display(v)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div></section>`;
}

export function audit({state}) {
  const roles=[['Leser','Se publiserte data og vurderinger'],['Informasjonsforvalter','Registrere og utbedre metadata'],['Informasjonsarkitekt','Forvalte modeller, begreper og relasjoner'],['Godkjenner','Godkjenne og publisere'],['Administrator','Alle demohandlinger']];
  return `${head('Styring og spor','Hvem bestemte hva — og hvorfor?','Endringer i demoen registreres med rolle, tidspunkt, ressurs og begrunnelse.')}<div class="audit-layout"><section class="panel"><h2>Revisjonsspor</h2><ol class="timeline">${state.audit.map(x=>`<li><span></span><div><small>${new Intl.DateTimeFormat('nb-NO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x.at))} · ${e(x.actor)}</small><strong>${e(x.action)}</strong><p>${e(x.subject)} — ${e(x.detail)}</p></div></li>`).join('')}</ol></section><aside class="panel governance"><p class="eyebrow">Styringsmodell</p><h2>Roller og grenser</h2>${roles.map(([r,d])=>`<div class="role"><strong>${r}</strong><span>${d}</span></div>`).join('')}<div class="limitation"><strong>Demo, ikke autorisasjon</strong><p>Rollebytte simulerer tilgang. En produksjonsløsning må bruke virksomhetsidentitet, serverhåndhevede roller og uforanderlig hendelseslogging.</p></div><button class="button secondary full" data-action="brief" data-id="CW-DOC-002">Eksporter eksempelnotat</button></aside></div>`;
}
