const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
function boot({saved=null,reduced=true}={}){
  const elements=new Map(),stored=new Map();if(saved)stored.set('vedtak-adventure-v1',JSON.stringify(saved));
  const element=id=>{if(!elements.has(id))elements.set(id,{id,textContent:'',innerHTML:'',style:{},dataset:{},disabled:false,classList:{add(){},remove(){},toggle(){},contains(){return true}},setAttribute(){},addEventListener(){},focus(){},getBoundingClientRect(){return {width:1280,height:720}},getContext(){return {}},parentElement:{getBoundingClientRect(){return {width:1280,height:720}}}});return elements.get(id)};
  const document={getElementById:element,querySelectorAll:()=>[],addEventListener(){},hidden:false};
  const sandbox={document,window:{},localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v)},Image:class{},ResizeObserver:class{observe(){}},matchMedia:()=>({matches:reduced}),addEventListener(){},requestAnimationFrame(){},setInterval(){},setTimeout(){},console,Math};
  let source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');
  source=source.replace('  updateContinue();requestAnimationFrame(frame);',`window.test={begin,resume,finish,loadLevel,update,damage,menu,keys,pressed,makeLevel,track,award,earnBadge,spectacle,get player(){return player},get level(){return level},get boss(){return boss},get save(){return save},get medals(){return runMedals},get levelDamage(){return levelDamage}};updateContinue();`);
  vm.runInNewContext(source,sandbox);return {api:sandbox.window.test,snapshot:sandbox.window.Vedtak.snapshot,rewards:sandbox.window.Vedtak.rewards,element,stored};
}
const step=(a,n)=>{for(let i=0;i<n;i++)a.update(1/60)};
test('double jump climbs; third jump is rejected; landing restores jumps',()=>{const {api:a}=boot();a.begin();a.resume();step(a,60);assert.equal(a.player.onGround,true);const ground=a.player.y;a.pressed.add('Space');step(a,12);assert.ok(a.player.y<ground-60);a.pressed.add('Space');step(a,1);assert.equal(a.player.jumps,2);step(a,8);const vy=a.player.vy;a.pressed.add('Space');step(a,1);assert.ok(a.player.vy>vy);step(a,100);assert.equal(a.player.jumps,0)});
test('dash has travel and cooldown; damage does not consume collected progress',()=>{const {api:a,snapshot}=boot();a.begin();a.resume();step(a,30);const start=a.player.x;a.pressed.add('KeyX');step(a,10);assert.ok(a.player.x-start>100);const cool=a.player.dashCool;a.pressed.add('KeyX');step(a,1);assert.ok(a.player.dashCool<cool);const item=a.level.pickups.find(p=>p.type==='letter');a.player.x=item.x;a.player.y=item.y;a.update(1/60);assert.equal(snapshot().trust,1);a.damage(true);assert.equal(snapshot().trust,1);assert.equal(snapshot().deaths,1)});
test('coffee heals and checkpoints restore health and recovery position',()=>{const {api:a,snapshot}=boot();a.begin();a.resume();a.player.hp=1;const item=a.level.pickups.find(p=>p.type==='coffee');a.player.x=item.x;a.player.y=item.y;step(a,1);assert.equal(a.player.hp,2);assert.ok(snapshot().coffee>9);const cp=a.level.checkpoints[0];a.player.x=cp.x+25;a.player.y=cp.y-58;step(a,1);assert.equal(snapshot().checkpoint,1);assert.equal(a.player.hp,3);a.damage(true);assert.ok(a.player.x>cp.x);assert.equal(a.player.hp,2)});
test('help cannot nest or reopen a completed chapter for duplicate points',()=>{const {api:a,element,snapshot}=boot();element('help').onclick();element('help').onclick();element('dialogAction').onclick();assert.equal(snapshot().mode,'menu');assert.doesNotThrow(()=>step(a,2));a.begin();a.resume();a.finish();const score=snapshot().score;element('help').onclick();assert.equal(snapshot().mode,'complete');step(a,2);assert.equal(snapshot().score,score)});
test('chapter damage medal counts ordinary hits and resets between chapters',()=>{const {api:a}=boot();a.begin();a.resume();a.player.invuln=0;a.damage();a.finish();assert.equal(a.medals[0],1);a.loadLevel(1);a.resume();assert.equal(a.levelDamage,0);a.finish();assert.equal(a.medals[1],2)});
test('boss resists closed attacks, accepts six open top hits, and permits final victory',()=>{const {api:a,snapshot,stored}=boot();a.begin(2);a.resume();const b=a.boss;const strike=()=>{a.player.x=b.x+55;a.player.y=b.y-a.player.h-2;a.player.vy=250;a.player.invuln=1;step(a,1)};b.timer=1;strike();assert.equal(b.hp,6);for(let i=0;i<6;i++){b.timer=3.4;b.invuln=0;strike()}assert.equal(b.hp,0);a.player.x=a.level.exit+1;step(a,1);assert.equal(snapshot().mode,'win');assert.ok(snapshot().score>4000);assert.ok(stored.size>0)});
test('every chapter has six unique trust letters, safe spawn, exit and bounded gaps',()=>{const {api:a}=boot();for(let i=0;i<3;i++){const l=a.makeLevel(i);assert.equal(l.pickups.filter(p=>p.type==='letter').length,6);assert.equal(new Set(l.pickups.filter(p=>p.type==='letter').map(p=>p.index)).size,6);const ground=l.platforms.filter(p=>p.y>=550).sort((p,q)=>p.x-q.x);for(let j=1;j<ground.length;j++)assert.ok(ground[j].x-(ground[j-1].x+ground[j-1].w)<=170);assert.ok(l.platforms.some(p=>l.exit>=p.x&&l.exit<p.x+p.w));}});
test('all level transitions lead to playable chapters and save the unlock',()=>{const {api:a,element,snapshot}=boot();a.begin();a.resume();for(let i=0;i<2;i++){a.finish();element('dialogAction').onclick();assert.equal(snapshot().level,i+1);assert.equal(snapshot().mode,'intro');element('dialogAction').onclick();assert.equal(snapshot().mode,'play');assert.equal(a.save.unlocked,i+1)}});

test('chapter goals reward once, reset per chapter, and preserve badge collection',()=>{const {api:a,snapshot,rewards}=boot();a.begin();a.resume();a.track('coins',20);assert.equal(rewards().quests[0].done,true);assert.equal(snapshot().score,700);assert.ok(rewards().badges.includes('start'));a.track('coins');assert.equal(snapshot().score,700);a.loadLevel(1);assert.ok(rewards().quests.every(q=>q.progress===0&&!q.done));assert.ok(rewards().badges.includes('start'))});
test('Fellesløft doubles points, attracts nearby glints, expires, and waits while paused',()=>{const {api:a,rewards}=boot();a.begin();a.resume();a.track('coins',30);assert.equal(rewards().boost,7);assert.equal(a.award(100,0,0),200);const glint=a.level.pickups.find(p=>p.type==='coin'&&p.x>200);a.player.x=glint.x-100;a.player.y=glint.y;const x=glint.x;step(a,1);assert.ok(glint.x<x);a.menu();const time=rewards().boost;step(a,60);assert.equal(rewards().boost,time);a.resume();a.player.x=90;a.player.y=552;step(a,430);assert.equal(rewards().boost,0);assert.equal(a.award(100,0,0),100)});
test('badges cannot be farmed in one round; ranks follow earned points',()=>{const {api:a,snapshot,rewards}=boot();a.begin();a.resume();a.earnBadge('secret');const first=snapshot().score;a.earnBadge('secret');assert.equal(snapshot().score,first);a.award(4000,0,0);assert.equal(rewards().rank,'Brobygger');a.begin();a.resume();a.earnBadge('secret');assert.equal(snapshot().score,400);assert.equal(rewards().badges.filter(b=>b==='secret').length,1)});
test('older saved progress migrates while audio defaults on and unknown badges are discarded',()=>{const {api:a}=boot({saved:{unlocked:2,best:9000,medals:[2,3,1],badges:['trust','injected'],music:false}});assert.equal(a.save.unlocked,2);assert.equal(a.save.best,9000);assert.equal(a.save.medals[1],3);assert.equal(a.save.music,false);assert.equal(a.save.effects,true);assert.deepEqual(Array.from(a.save.badges),['trust'])});
test('celebrations remain bounded and reduced motion removes shockwave rings',()=>{const normal=boot({reduced:false}),calm=boot({reduced:true});for(const h of [normal,calm]){h.api.begin();h.api.resume();for(let i=0;i<25;i++)h.api.spectacle(100,100,'#fff',3);assert.ok(h.rewards().particles<=520);assert.ok(h.rewards().rings<=12)}assert.ok(normal.rewards().rings>0);assert.equal(calm.rewards().rings,0)});
test('badges dialog restores title mode without inventing a player',()=>{const {element,snapshot,api:a}=boot();element('collection').onclick();assert.equal(snapshot().mode,'badges');element('collection').onclick();element('dialogAction').onclick();assert.equal(snapshot().mode,'menu');assert.doesNotThrow(()=>step(a,2))});
