import {roomStories,newProgress,restoreRooms,investigated,roomComplete,finalQuiz} from './room-stories';
import type {RoomProgress} from './room-stories';
import {renderRoom,renderFinale} from './room-experience';
import missionData from '../cases/missions.json';
import {emptyJourney,restoreJourney,planText} from './journey-state';
import type {Mission,JourneyState} from './journey-state';
import type {MuseumCase} from './types';
export const missions:Mission[]=missionData;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const $=<E extends HTMLElement>(s:string)=>document.querySelector<E>(s)!;
const storageKey='arkivmuseet-journey-v1';
type Hooks={read:(c:MuseumCase)=>void;sources:(c:MuseumCase)=>void;next:(id:string)=>void;plan:()=>void;announce:(s:string)=>void;stage:(id:string,safe:boolean|null)=>void;dialog:(title:string,body:string)=>void};
export class Journey{
  state:JourneyState=emptyJourney();storageAvailable=true;rooms:Record<string,RoomProgress>={};feedback:Record<string,string>={};finalAnswers:(number|null)[]=[null,null];finalMessage='';
  constructor(public cases:MuseumCase[],public hooks:Hooks){try{this.state=restoreJourney(localStorage.getItem(storageKey),missions);const raw=localStorage.getItem('arkivmuseet-narrative-v2');this.rooms=restoreRooms(raw,missions);const stored=JSON.parse(raw||'null');if(this.count()===5&&Array.isArray(stored?.finalAnswers)){for(let i=0;i<2;i++){if(i&&this.finalAnswers[0]!==finalQuiz[0].answer)break;const n=stored.finalAnswers[i];if(Number.isInteger(n)&&n>=0&&n<finalQuiz[i].options.length)this.finalAnswers[i]=n;}}}catch{this.storageAvailable=false;}}
  save(){for(const s of roomStories)this.sync(s.id);try{localStorage.setItem(storageKey,JSON.stringify(this.state));localStorage.setItem('arkivmuseet-narrative-v2',JSON.stringify({version:2,rooms:this.rooms,finalAnswers:this.finalAnswers}));}catch{this.storageAvailable=false;}this.updateHud();}
  completed(id:string){const s=roomStories.find(s=>s.id===id),p=this.rooms[id];return !!s&&!!p&&p.phase===5&&roomComplete(s,p,this.mission(id).options);}
  count(){return roomStories.filter(s=>this.completed(s.id)).length;}
  nextId(){return missions.find(m=>!this.completed(m.id))?.id??'leader';}
  updateHud(){const button=document.querySelector<HTMLButtonElement>('#passport-open');if(button)button.textContent=`Reisepass ${this.count()} / ${missions.length}`;const progress=document.querySelector<HTMLProgressElement>('#journey-progress');if(progress)progress.value=this.count();const label=document.querySelector('#journey-status');if(label)label.textContent=this.count()===5?'Fem læringsmerker samlet. Sluttrommet er åpent.':`${this.count()} av 5 rom løst · Samle alle for å åpne sluttrommet`;}
  mission(id:string){return missions.find(m=>m.id===id)!;}
  sync(id:string){const p=this.rooms[id];if(!p)return;const m=this.mission(id),s=roomStories.find(s=>s.id===id)!;this.state.attempts[id]={selected:investigated(s,p)?m.clues.filter(c=>c.relevant).map(c=>c.id):[],checked:investigated(s,p),choice:p.choice,turn:p.turn,completed:this.completed(id)};}
  render(c:MuseumCase,focus=false){renderRoom(this,c,focus);}
  finale(){renderFinale(this);}
  recap(c:MuseumCase){const s=roomStories.find(s=>s.id===c.id)!;this.hooks.dialog('Saken og lærdommen · '+c.organization,`<p class="lead">${esc(s.title)}</p><p>${esc(s.opening)}</p><h3>Problemet</h3><p>${esc(s.problem)}</p><h3>Lærdommen</h3><p>${esc(s.moral)}</p><p>${esc(s.transfer)}</p><p class="note">${esc(c.consequence[0].text)}</p><p>Museets faglige tolkning er skilt fra historiske funn. Senere utbedring er ikke undersøkt.</p><a href="${esc(c.sources[0].url)}" target="_blank" rel="noopener noreferrer">${esc(c.sources[0].institution)} · ${esc(c.sources[0].locator)} ↗</a>`);}
  compare(m:Mission,chosen:number){const recommended=m.options.findIndex(o=>o.protected);const alternate=chosen===recommended?m.options.findIndex(o=>!o.protected):recommended;this.hooks.dialog('Samme situasjon. To mulige forløp.',`<p>Tenkte konsekvenser for å undersøke ledergrepene. Ingen beregning av faktisk risiko.</p><div class="path-comparison">${[chosen,alternate].map((i,n)=>`<section><p class="eyebrow">${n===0?'DITT VALG':'ET ANNET VALG'}</p><h3>${esc(m.options[i].title)}</h3><ol>${m.options[i].timeline.map(e=>`<li><strong>${esc(e.when)} · ${esc(e.title)}</strong><p>${esc(e.text)}</p></li>`).join('')}</ol></section>`).join('')}</div>`);}
  passport(){this.hooks.dialog('Reisepasset ditt',`<p class="lead">${this.count()} av 5 læringsmerker samlet</p><p>Løs undersøkelsen, prøv et ledervalg og bestå to spørsmål i hvert rom. Fem merker åpner sluttrommet. Du kan besøke rommene i hvilken rekkefølge du vil.</p><div class="passport-list">${missions.map((m,i)=>`<button data-passport="${m.id}" class="${this.completed(m.id)?'earned':''}"><span>${this.completed(m.id)?'✓':String(i+1).padStart(2,'0')}</span><span><strong>${esc(m.badge)}</strong><small>${esc(m.title)}</small></span><span>→</span></button>`).join('')}</div><p class="caption">Merkene viser gjennomførte øvelser. De er ikke en vurdering av virksomheten din.</p><p>${this.storageAvailable?'Fremdrift og lederbestilling lagres bare i denne nettleseren.':'Lagring er ikke tilgjengelig. Fremdriften beholdes mens siden er åpen.'}</p><button id="passport-plan" class="primary">Min lederbestilling →</button><p><button id="reset-journey">Start reisen på nytt …</button></p>`);document.querySelectorAll<HTMLButtonElement>('[data-passport]').forEach(b=>b.onclick=()=>this.hooks.next(b.dataset.passport!));$('#passport-plan').onclick=this.hooks.plan;$('#reset-journey').onclick=()=>{this.hooks.dialog('Start reisen på nytt?',`<p>Dette fjerner læringsmerker, valg og lederbestillingen fra denne nettleseren.</p><button id="confirm-reset">Ja, start på nytt</button> <button id="cancel-reset" class="primary">Behold reisen</button>`);$('#cancel-reset').onclick=()=>this.passport();$('#confirm-reset').onclick=()=>{this.state=emptyJourney();this.rooms={};this.finalAnswers=[null,null];this.finalMessage='';this.feedback={};this.save();this.hooks.next(missions[0].id);};};}
  plan(){this.hooks.dialog('Min lederbestilling',`<p class="lead">Fra museumsbesøk til neste ledermøte.</p><p>Velg ett eller flere tiltak. Avtal ansvarlig rolle og oppfølging. Skriv ingen saksopplysninger.</p><form id="action-plan">${missions.map(m=>{const p=this.state.plan[m.id]??{selected:false,owner:'',due:''};return `<section class="plan-item"><label class="plan-select"><input type="checkbox" data-plan="${m.id}" ${p.selected?'checked':''}><strong>${esc(m.badge)}</strong></label><p>${esc(m.action)}</p><p class="plan-proof"><strong>Be om å få se:</strong> ${esc(m.proof)}</p><div class="plan-fields"><label>Ansvarlig rolle<input type="text" maxlength="100" autocomplete="off" data-owner="${m.id}" placeholder="F.eks. systemeier" value="${esc(p.owner)}"></label><label>Oppfølging<input type="date" data-due="${m.id}" value="${esc(p.due)}"></label></div></section>`;}).join('')}</form><p id="plan-storage" class="caption">${this.storageAvailable?'Valgene lagres bare i denne nettleseren.':'Lagring er ikke tilgjengelig. Last ned bestillingen før du lukker siden.'}</p><p id="plan-status" role="status"></p><div class="plan-actions"><button id="download-plan" class="primary">Last ned bestillingen ↓</button><button id="print-plan">Skriv ut / lagre PDF</button></div>`);
    const update=()=>{missions.forEach(m=>{this.state.plan[m.id]={selected:$<HTMLInputElement>(`[data-plan="${m.id}"]`).checked,owner:$<HTMLInputElement>(`[data-owner="${m.id}"]`).value,due:$<HTMLInputElement>(`[data-due="${m.id}"]`).value};});this.save();if(!this.storageAvailable)$('#plan-storage').textContent='Lagring er ikke tilgjengelig. Last ned bestillingen før du lukker siden.';const n=missions.filter(m=>this.state.plan[m.id].selected).length;$<HTMLButtonElement>('#download-plan').disabled=n===0;$<HTMLButtonElement>('#print-plan').disabled=n===0;$('#plan-status').textContent=n?`${n} tiltak valgt.`:'Velg minst ett tiltak.';};
    $('#action-plan').oninput=update;$('#action-plan').onsubmit=e=>e.preventDefault();update();
    $('#download-plan').onclick=()=>{const url=URL.createObjectURL(new Blob([planText(missions,this.state)],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Arkivmuseet-lederbestilling.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#plan-status').textContent='Bestillingen er klargjort for nedlasting.';};
    $('#print-plan').onclick=()=>{document.querySelector('#print-order')?.remove();const sheet=document.createElement('section');sheet.id='print-order';const title=document.createElement('h1');title.textContent='Min lederbestilling';const content=document.createElement('pre');content.textContent=planText(missions,this.state);sheet.append(title,content);document.body.append(sheet);window.print();};
  }
}
