import missionData from '../cases/missions.json';
import {emptyAttempt,emptyJourney,restoreJourney,evidenceCorrect,canComplete,planText} from './journey-state';
import type {Mission,JourneyState} from './journey-state';
import type {MuseumCase} from './types';
export const missions:Mission[]=missionData;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const $=<E extends HTMLElement>(s:string)=>document.querySelector<E>(s)!;
const storageKey='arkivmuseet-journey-v1';
type Hooks={read:(c:MuseumCase)=>void;sources:(c:MuseumCase)=>void;next:(id:string)=>void;plan:()=>void;announce:(s:string)=>void;stage:(id:string,safe:boolean|null)=>void;dialog:(title:string,body:string)=>void};
export class Journey{
  state:JourneyState=emptyJourney();storageAvailable=true;
  constructor(public cases:MuseumCase[],public hooks:Hooks){try{this.state=restoreJourney(localStorage.getItem(storageKey),missions);}catch{this.storageAvailable=false;}}
  save(){try{localStorage.setItem(storageKey,JSON.stringify(this.state));}catch{this.storageAvailable=false;}this.updateHud();}
  completed(id:string){return this.state.attempts[id]?.completed===true;}
  count(){return missions.filter(m=>this.completed(m.id)).length;}
  nextId(){return missions.find(m=>!this.completed(m.id))?.id??'leader';}
  updateHud(){const button=document.querySelector<HTMLButtonElement>('#passport-open');if(button)button.textContent=`Reisepass ${this.count()} / ${missions.length}`;const progress=document.querySelector<HTMLProgressElement>('#journey-progress');if(progress)progress.value=this.count();const label=document.querySelector('#journey-status');if(label)label.textContent=this.count()===5?'Fem læringsmerker samlet. Velg tiltak for hverdagen.':`${this.count()} av 5 oppdrag løst · Ingen tidsfrist`;}
  render(c:MuseumCase,focus=false){
    const m=missions.find(m=>m.id===c.id)!;
    const a=this.state.attempts[m.id]??=emptyAttempt();
    const phase=a.completed?3:a.choice!==null?2:a.checked?1:0;
    $('#story-kicker').textContent=`OPPDRAG ${missions.indexOf(m)+1} / 5 · ${m.badge}`;
    const media=c.image?`<figure class="case-photo"><button id="photo-expand" aria-label="Forstørr bildet: ${esc(c.image.alt)}"><img src="${import.meta.env.BASE_URL}${esc(c.image.src)}" alt="${esc(c.image.alt)}" width="${c.image.width}" height="${c.image.height}" decoding="async"><span>Se stort ↗</span></button><figcaption>${esc(c.image.caption)} <a href="${esc(c.image.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(c.image.credit)}</a> · <a href="${esc(c.image.licenseUrl)}" target="_blank" rel="noopener noreferrer">${esc(c.image.license)}</a></figcaption></figure>`:'';
    $('#story-content').innerHTML=`<div class="mission-tabs"><button id="mission-read">Den virkelige saken ↗</button><button id="mission-source">Kilder ↗</button></div><ol class="mission-steps" aria-label="Oppdragets deler">${['Finn spor','Ta et valg','Se følgene','Ta med videre'].map((s,i)=>`<li class="${phase===i?'current':phase>i?'done':''}" ${phase===i?'aria-current="step"':''}><span>${phase>i?'✓':i+1}</span>${s}</li>`).join('')}</ol><p class="simulation-label">LEDERØVELSE · TENKT SITUASJON</p><h2 id="mission-title" tabindex="-1">${esc(m.title)}</h2>${phase===0?`${media}<details class="case-context"><summary>Virkelig sak · ${esc(c.organization)} · ${esc(c.eventDate)}</summary><p>${esc(c.shortNarrative.text)}</p><p>${esc(c.consequence[0].text)}</p><a href="${esc(c.sources[0].url)}" target="_blank" rel="noopener noreferrer">${esc(c.sources[0].institution)} · ${esc(c.shortNarrative.locator)} ↗</a></details><p class="mission-brief">${esc(m.brief)}</p><p class="mission-task">${esc(m.task)}</p><div class="clue-grid">${m.clues.map((cl,i)=>`<label class="clue"><input type="checkbox" data-clue="${cl.id}" ${a.selected.includes(cl.id)?'checked':''}><span class="clue-number">SPOR 0${i+1}</span><strong>${esc(cl.title)}</strong><span>${esc(cl.detail)}</span></label>`).join('')}</div><p id="evidence-feedback" class="evidence-feedback" role="status">Velg to spor. Du kan prøve så mange ganger du vil.</p>`:''}${phase===1?`<p class="mission-brief">${esc(m.brief)}</p><div class="evidence-success"><strong>✓ Du fant de avgjørende sporene</strong><p>${m.clues.filter(cl=>cl.relevant).map(cl=>esc(cl.feedback)).join(' ')}</p></div><h3>${esc(m.decision)}</h3><div class="decision-options">${m.options.map((o,i)=>`<button data-decision="${i}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span><strong>${esc(o.title)}</strong><small>${esc(o.tradeoff)}</small></span><span aria-hidden="true">→</span></button>`).join('')}</div>`:''}${phase===2?this.consequence(m):''}${phase===3?`<div class="mission-earned"><span class="earned-check" aria-hidden="true">✓</span><p>LÆRINGSMERKE SAMLET</p><h3>${esc(m.badge)}</h3><p>Du har funnet sporene, prøvd et ledervalg og fulgt konsekvensene.</p></div><div class="takeaway"><span class="eyebrow">TA MED TIL NESTE LEDERMØTE</span><h3>${esc(m.action)}</h3><p><strong>Be om å få se:</strong> ${esc(m.proof)}</p><button id="mission-add" class="primary">${this.state.plan[m.id]?.selected?'✓ Lagt i lederbestillingen':'Legg i min lederbestilling'} +</button></div><div class="historical-fact"><span class="eyebrow">DETTE ER DOKUMENTERT · ${esc(c.organization)}</span><p>${esc(c.shortNarrative.text)}</p><p class="case-boundary">${esc(c.consequence[0].text)}</p><button id="earned-source">Les originalkilden ↗</button></div>`:''}`;
    const nextCase=this.cases[this.cases.findIndex(x=>x.id===c.id)+1]?.id??'leader';
    $('#story-nav').innerHTML=phase===0?`<span>Undersøk · velg · prøv</span><button id="check-evidence" class="primary">Prøv sporene →</button>`:phase===1?`<button id="back-evidence">← Se sporene igjen</button><span>Hva vil du bestille?</span>`:phase===2?`<button id="rewind-choice">← Prøv et annet valg</button>${a.turn<2?'<button id="advance-time" class="primary">Spol frem →</button>':`<button id="finish-mission" class="primary">${m.options[a.choice!].protected?'Samle læringsmerket ✓':'Finn et bedre grep ↺'}</button>`}`:`<button id="show-plan">Min lederbestilling</button><button id="next-mission" class="primary">${nextCase==='leader'?'Til Lederens rom':'Neste oppdrag'} →</button>`;
    $('#mission-read').onclick=()=>this.hooks.read(c);$('#mission-source').onclick=()=>this.hooks.sources(c);
    if(c.image)document.querySelector<HTMLButtonElement>('#photo-expand')?.addEventListener('click',()=>this.hooks.dialog('Bildet fra saken',`<figure class="expanded-photo"><img src="${import.meta.env.BASE_URL}${esc(c.image!.src)}" alt="${esc(c.image!.alt)}"><figcaption>${esc(c.image!.caption)}<p><a href="${esc(c.image!.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(c.image!.credit)} · ${esc(c.image!.license)}</a></p></figcaption></figure>`));
    if(phase===0){
      document.querySelectorAll<HTMLInputElement>('[data-clue]').forEach(input=>input.onchange=()=>{a.selected=Array.from(document.querySelectorAll<HTMLInputElement>('[data-clue]:checked')).map(el=>el.dataset.clue!);this.save();});
      $('#check-evidence').onclick=()=>{if(evidenceCorrect(m,a.selected)){a.checked=true;this.save();this.render(c,true);this.hooks.announce('Du fant de to avgjørende sporene. Ta et ledervalg.');}else{const selected=m.clues.filter(cl=>a.selected.includes(cl.id));$('#evidence-feedback').innerHTML=`<strong>${a.selected.length!==2?'Velg akkurat to spor.':'Se en gang til.'}</strong> ${selected.filter(cl=>!cl.relevant).map(cl=>esc(cl.feedback)).join(' ')||'Se etter bevis på at informasjonen kan finnes og brukes, ikke bare at en oppgave er utført.'}`;}};
    }else if(phase===1){
      $('#back-evidence').onclick=()=>{a.checked=false;this.save();this.render(c,true);};
      document.querySelectorAll<HTMLButtonElement>('[data-decision]').forEach(b=>b.onclick=()=>{a.choice=Number(b.dataset.decision);a.turn=0;this.save();this.hooks.stage(c.id,m.options[a.choice].protected);this.render(c,true);});
    }else if(phase===2){
      $('#rewind-choice').onclick=()=>{a.choice=null;a.turn=0;this.hooks.stage(c.id,null);this.save();this.render(c,true);};
      document.querySelector<HTMLButtonElement>('#advance-time')?.addEventListener('click',()=>{a.turn++;this.save();this.render(c,true);this.hooks.announce(m.options[a.choice!].timeline[a.turn].title);});
      document.querySelector<HTMLButtonElement>('#finish-mission')?.addEventListener('click',()=>{if(canComplete(m,a)){a.completed=true;this.save();this.render(c,true);this.hooks.announce(`Læringsmerke samlet: ${m.badge}. ${this.count()} av 5 oppdrag løst.`);}else{a.choice=null;a.turn=0;this.save();this.render(c,true);}});
      document.querySelector<HTMLButtonElement>('#compare-paths')?.addEventListener('click',()=>this.compare(m,a.choice!));
    }else{
      $('#mission-add').onclick=()=>{const p=this.state.plan[m.id]??={selected:false,owner:'',due:''};p.selected=!p.selected;this.save();this.render(c);$('#mission-add').focus();};
      $('#show-plan').onclick=this.hooks.plan;$('#next-mission').onclick=()=>this.hooks.next(nextCase);$('#earned-source').onclick=()=>this.hooks.sources(c);
    }
    this.updateHud();if(focus){$('#story-content').scrollTop=0;$('#mission-title').focus({preventScroll:true});}
  }
  consequence(m:Mission){const a=this.state.attempts[m.id],o=m.options[a.choice!],event=o.timeline[a.turn];return `<div class="chosen-decision"><span>DITT VALG</span><p>${esc(o.title)}</p></div><div class="time-machine ${o.protected?'protected':'fragile'}"><div class="time-rail" aria-label="Tidspunkt ${a.turn+1} av 3">${o.timeline.map((e,i)=>`<span class="${i<=a.turn?'passed':''}">${i+1}<small>${esc(e.when)}</small></span>`).join('')}</div><p class="eyebrow">${esc(event.when)}</p><h3>${esc(event.title)}</h3><p class="future-event">${esc(event.text)}</p><p class="simulation-footnote">Mulig følge i øvelsen. Ikke et faktisk hendelsesforløp.</p></div>${a.turn===2?`<div class="debrief"><strong>${o.protected?'Du har bestilt en kontroll av resultatet.':'Hva ville gjort sporene mer robuste?'}</strong><p>${esc(m.proof)}</p><button id="compare-paths">Sammenlign to forløp ↔</button></div>`:'<p class="caption">Trykk «Spol frem» for å se hva valget kan bety senere.</p>'}`;}
  compare(m:Mission,chosen:number){const recommended=m.options.findIndex(o=>o.protected);const alternate=chosen===recommended?m.options.findIndex(o=>!o.protected):recommended;this.hooks.dialog('Samme situasjon. To mulige forløp.',`<p>Tenkte konsekvenser for å undersøke ledergrepene. Ingen beregning av faktisk risiko.</p><div class="path-comparison">${[chosen,alternate].map((i,n)=>`<section><p class="eyebrow">${n===0?'DITT VALG':'ET ANNET VALG'}</p><h3>${esc(m.options[i].title)}</h3><ol>${m.options[i].timeline.map(e=>`<li><strong>${esc(e.when)} · ${esc(e.title)}</strong><p>${esc(e.text)}</p></li>`).join('')}</ol></section>`).join('')}</div>`);}
  passport(){this.hooks.dialog('Reisepasset ditt',`<p class="lead">${this.count()} av 5 læringsmerker samlet</p><p>Velg et rom. Du kan besøke dem i hvilken rekkefølge du vil.</p><div class="passport-list">${missions.map((m,i)=>`<button data-passport="${m.id}" class="${this.completed(m.id)?'earned':''}"><span>${this.completed(m.id)?'✓':String(i+1).padStart(2,'0')}</span><span><strong>${esc(m.badge)}</strong><small>${esc(m.title)}</small></span><span>→</span></button>`).join('')}</div><p class="caption">Merkene viser gjennomførte øvelser. De er ikke en vurdering av virksomheten din.</p><p>${this.storageAvailable?'Fremdrift og lederbestilling lagres bare i denne nettleseren.':'Lagring er ikke tilgjengelig. Fremdriften beholdes mens siden er åpen.'}</p><button id="passport-plan" class="primary">Min lederbestilling →</button><p><button id="reset-journey">Start reisen på nytt …</button></p>`);document.querySelectorAll<HTMLButtonElement>('[data-passport]').forEach(b=>b.onclick=()=>this.hooks.next(b.dataset.passport!));$('#passport-plan').onclick=this.hooks.plan;$('#reset-journey').onclick=()=>{this.hooks.dialog('Start reisen på nytt?',`<p>Dette fjerner læringsmerker, valg og lederbestillingen fra denne nettleseren.</p><button id="confirm-reset">Ja, start på nytt</button> <button id="cancel-reset" class="primary">Behold reisen</button>`);$('#cancel-reset').onclick=()=>this.passport();$('#confirm-reset').onclick=()=>{this.state=emptyJourney();this.save();this.hooks.next(missions[0].id);};};}
  plan(){this.hooks.dialog('Min lederbestilling',`<p class="lead">Fra museumsbesøk til neste ledermøte.</p><p>Velg ett eller flere tiltak. Avtal ansvarlig rolle og oppfølging. Skriv ingen saksopplysninger.</p><form id="action-plan">${missions.map(m=>{const p=this.state.plan[m.id]??{selected:false,owner:'',due:''};return `<section class="plan-item"><label class="plan-select"><input type="checkbox" data-plan="${m.id}" ${p.selected?'checked':''}><strong>${esc(m.badge)}</strong></label><p>${esc(m.action)}</p><p class="plan-proof"><strong>Be om å få se:</strong> ${esc(m.proof)}</p><div class="plan-fields"><label>Ansvarlig rolle<input type="text" maxlength="100" autocomplete="off" data-owner="${m.id}" placeholder="F.eks. systemeier" value="${esc(p.owner)}"></label><label>Oppfølging<input type="date" data-due="${m.id}" value="${esc(p.due)}"></label></div></section>`;}).join('')}</form><p id="plan-storage" class="caption">${this.storageAvailable?'Valgene lagres bare i denne nettleseren.':'Lagring er ikke tilgjengelig. Last ned bestillingen før du lukker siden.'}</p><p id="plan-status" role="status"></p><div class="plan-actions"><button id="download-plan" class="primary">Last ned bestillingen ↓</button><button id="print-plan">Skriv ut / lagre PDF</button></div>`);
    const update=()=>{missions.forEach(m=>{this.state.plan[m.id]={selected:$<HTMLInputElement>(`[data-plan="${m.id}"]`).checked,owner:$<HTMLInputElement>(`[data-owner="${m.id}"]`).value,due:$<HTMLInputElement>(`[data-due="${m.id}"]`).value};});this.save();if(!this.storageAvailable)$('#plan-storage').textContent='Lagring er ikke tilgjengelig. Last ned bestillingen før du lukker siden.';const n=missions.filter(m=>this.state.plan[m.id].selected).length;$<HTMLButtonElement>('#download-plan').disabled=n===0;$<HTMLButtonElement>('#print-plan').disabled=n===0;$('#plan-status').textContent=n?`${n} tiltak valgt.`:'Velg minst ett tiltak.';};
    $('#action-plan').oninput=update;$('#action-plan').onsubmit=e=>e.preventDefault();update();
    $('#download-plan').onclick=()=>{const url=URL.createObjectURL(new Blob([planText(missions,this.state)],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Arkivmuseet-lederbestilling.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#plan-status').textContent='Bestillingen er klargjort for nedlasting.';};
    $('#print-plan').onclick=()=>{document.querySelector('#print-order')?.remove();const sheet=document.createElement('section');sheet.id='print-order';const title=document.createElement('h1');title.textContent='Min lederbestilling';const content=document.createElement('pre');content.textContent=planText(missions,this.state);sheet.append(title,content);document.body.append(sheet);window.print();};
  }
}
