import './style.css';
import './journey.css';
import records from '../cases/cases.json';
import legalRecords from '../cases/legal-sources.json';
import type {MuseumCase,Claim,Source} from './types';
import type {MuseumWorld} from './world';
import {MuseumAudio} from './audio';
import {Journey,missions} from './journey';
const cases=records as MuseumCase[],legalSources=legalRecords as Source[];
const $=<E extends HTMLElement>(s:string)=>document.querySelector<E>(s)!;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const sound=new MuseumAudio();let world:MuseumWorld|null=null;let flatMode=false;let active=false,guided=false,current:MuseumCase|null=null,step=0,tourIndex=0,near:string|null=null,viewOpen=false;let scenario=0,choice:number|null=null;let returningFocus:HTMLElement|null=null;
const date=(s:string)=>/^\d{4}-\d\d-\d\d$/.test(s)?new Date(s+'T12:00:00').toLocaleDateString('nb-NO'):s;
import scenarios from '../cases/leader-scenarios.json';
$('#app').innerHTML=`
 <canvas id="world" aria-label="Tredimensjonalt museum. Bruk WASD for å gå og dra for å se deg rundt." tabindex="-1"></canvas>
 <div class="shade" id="shade"></div><div id="curtain" aria-hidden="true"></div>
 <header class="masthead"><a class="brand" href="${import.meta.env.BASE_URL}" aria-label="Arkivmuseet, start"><span class="monogram">A</span><span>ARKIVMUSEET<small>Et museum for samfunnets hukommelse</small></span></a><span class="edition">DIGITAL UTSTILLING <i></i> 2026</span><div id="toolbar" hidden><button id="passport-open">Reisepass 0 / 5</button><button id="map-open">Romoversikt</button><button id="menu-open" aria-label="Pause og innstillinger">Meny <span aria-hidden="true">☰</span></button></div></header>
 <main id="intro"><p class="eyebrow"><span class="line"></span> DOKUMENTASJON · OFFENTLIGHET · TILLIT</p><h1>ARKIV<span>MUSEET</span></h1><h2>Sporene staten ikke<br>hadde råd til å miste</h2><p class="intro-copy">Du er lederen. Finn sporene, ta valgene og spol frem til følgene. Fem virkelige saker. Fem oppdrag som begynner i museet og fortsetter på jobb.</p><div class="entry-actions"><button class="primary" id="guided" disabled>START LEDERREISEN <span>→</span></button><button id="enter" disabled>UTFORSK FRITT <span>↗</span></button></div><p class="entry-note">Ingen forkunnskaper. Ingen tidspress. Prøv et annet valg når du vil.</p><button class="about-link" id="flat-enter">SPILL UTEN 3D</button> · <button class="about-link" id="about">OM PROSJEKTET</button><p id="loading" role="status"><span class="loading-dot"></span> Museet åpner …</p></main>
 <div class="intro-footer" id="intro-footer"><span>FEM VIRKELIGE SAKER. ETT FELLES SPØRSMÅL.</span><span>Hva står igjen når sporene forsvinner?</span></div>
 <div id="hud" hidden><div class="journey-hud"><p id="journey-status">0 av 5 oppdrag løst · Ingen tidsfrist</p><progress id="journey-progress" max="5" value="0" aria-label="Oppdrag løst"></progress><button id="continue-journey">Til neste oppdrag →</button></div><div class="room-tag"><span id="room-kicker">VESTIBYLEN</span><strong id="room-title">Samfunnets hukommelse</strong></div><div id="reticle" aria-hidden="true">·</div><div id="near-card" hidden><span class="eyebrow" id="near-wing"></span><h2 id="near-title"></h2><button id="exhibit-open" class="primary">Prøv lederoppdraget <span>E ↗</span></button></div><div class="bottom-bar"><span id="controls-hint"><kbd>W A S D</kbd> Gå <span>·</span> Dra for å se <span>·</span> <kbd>E</kbd> Utforsk</span><div><button id="home">Hovedhall</button><button id="tour-toggle">Start omvisning</button><button id="audio-toggle" aria-pressed="false">Lyd av</button></div></div><div id="touch-controls" aria-label="Bevegelse"><button data-key="KeyW" aria-label="Gå frem">↑</button><div><button data-key="KeyA" aria-label="Gå til venstre">←</button><button data-key="KeyS" aria-label="Gå tilbake">↓</button><button data-key="KeyD" aria-label="Gå til høyre">→</button></div></div><p class="sound-caption" id="sound-caption" hidden>[Svak romlyd. Fottrinn når du går.]</p></div>
 <aside id="story" hidden aria-label="Utstilling og lederoppdrag"><div class="story-top"><span id="story-kicker" class="eyebrow"></span><button id="story-close" aria-label="Lukk utstillingen">×</button></div><div id="story-content"></div><div id="story-nav"></div></aside>
 <dialog id="dialog" aria-labelledby="dialog-title"><div class="dialog-header"><h2 id="dialog-title"></h2><button id="dialog-close" aria-label="Lukk vinduet">×</button></div><div id="dialog-body"></div></dialog>
 <div id="announce" class="sr-only" role="status" aria-live="polite"></div>`;

const journey=new Journey(cases,{read:c=>{current=c;step=0;renderStory();},sources:c=>sources(c),next:id=>{if(($('#dialog') as HTMLDialogElement).open)closeDialog();tourIndex=cases.findIndex(c=>c.id===id);void navigate(id,true);},plan:()=>journey.plan(),announce,stage:(id,safe)=>world?.setOutcome(id,safe),dialog:showDialog});
journey.updateHud();
$('#passport-open').onclick=()=>journey.passport();
$('#continue-journey').onclick=()=>void navigate(journey.nextId(),true);
function announce(s:string){$('#announce').textContent=s;}
function pause(p:boolean){world?.setPaused(p||flatMode);sound.pause(p);}
function showDialog(title:string,body:string){if(!($('#dialog') as HTMLDialogElement).open)returningFocus=document.activeElement as HTMLElement;pause(true);$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;($('#dialog') as HTMLDialogElement).showModal();}
function closeDialog(){($('#dialog') as HTMLDialogElement).close();pause(viewOpen);if(returningFocus?.isConnected)returningFocus.focus();else if(viewOpen)$('#story-close').focus();}
$('#dialog-close').onclick=closeDialog;($('#dialog') as HTMLDialogElement).addEventListener('cancel',e=>{e.preventDefault();closeDialog();});
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function about(){showDialog('Et museum for det som kan etterprøves',`<p class="lead">Dokumentasjon → hukommelse → kontroll → rettigheter → læring → ansvar → tillit.</p><p>Arkivmuseet er et uavhengig, digitalt formidlingsprosjekt i Rolf Selås’ prosjektsamling. Det er ikke en utstilling fra Nasjonalarkivet eller de omtalte virksomhetene.</p><p>Fem norske saker bygger på primærkilder. Funn, usikkerhet og museets lederlærdommer holdes adskilt. Historiske funn sier ikke hva tilstanden er i virksomheten i dag.</p><p>Arkitektur, gjenstander og lyd er laget for utstillingen. Installasjonene er <strong>visuelle rekonstruksjoner</strong>; de er ikke originaldokumenter. Fotografier og faksimiler er merket med motiv, dato, kilde og kreditering.</p><p>Du kan gå selv eller velge guidet visning. All faglig informasjon finnes også i tekst. Ingen innlogging, analyseverktøy eller KI-kall. Innstillinger, fremdrift og lederbestilling lagres bare i denne nettleseren.</p><a class="button primary" href="${import.meta.env.BASE_URL}tekst.html">Åpne hele tekstversjonen ↗</a><p><button id="all-sources">Se kilder og regelverk</button></p>`);$('#all-sources').onclick=()=>sources();}
$('#about').onclick=about;
function begin(tour:boolean,flat=false){if(!world&&!flat)return;flatMode=flat;document.body.classList.toggle('flat-mode',flat);active=true;guided=tour;$('#intro').hidden=true;$('#intro-footer').hidden=true;$('.edition').hidden=true;$('#toolbar').hidden=false;$('#hud').hidden=false;$('#shade').classList.add('playing');document.body.classList.add('playing');world?.start(tour);if(flat)world?.setPaused(true);$('#world').focus();$('#tour-toggle').textContent=tour?'Avslutt omvisning':'Start omvisning';$('#controls-hint').textContent=tour?'Omvisning · Ta den tiden du trenger.':'WASD · Gå     Dra · Se     E · Utforsk';if(tour){tourIndex=Math.max(0,cases.findIndex(c=>c.id===journey.nextId()));void navigate(journey.nextId(),true);}else announce('Velkommen. Gå frem til hovedhallen. Du kan også velge et rom fra romoversikten.');}
$('#enter').onclick=()=>begin(false);$('#guided').onclick=()=>begin(true);$('#flat-enter').onclick=()=>begin(true,true);
async function navigate(id:string,open=false){closeStory();if(!world||flatMode){if(open)openStory(id);return;}pause(false);$('#curtain').classList.add('transition');if(!world.settings.reduced)await new Promise(r=>setTimeout(r,350));const old=world.settings.reduced;world.settings.reduced=true;world.visit(id);world.settings.reduced=old;$('#curtain').classList.remove('transition');$('#room-kicker').textContent=id==='leader'?'V · LEDERENS ROM':cases.find(c=>c.id===id)!.wing;$('#room-title').textContent=id==='leader'?'Det neste arkivet skapes nå':cases.find(c=>c.id===id)!.title;if(open)openStory(id);}
function nearChanged(id:string|null){near=id;$('#near-card').hidden=!id||viewOpen||guided;if(id){$('#near-wing').textContent=id==='leader'?'V · Lederens rom':cases.find(c=>c.id===id)!.wing;$('#near-title').textContent=id==='leader'?'Det neste arkivet skapes nå':cases.find(c=>c.id===id)!.title;$('#room-kicker').textContent=id==='leader'?'V · Lederens rom':cases.find(c=>c.id===id)!.wing;$('#room-title').textContent=id==='leader'?'Det neste arkivet skapes nå':cases.find(c=>c.id===id)!.title;}else{$('#room-kicker').textContent='HOVEDHALLEN';$('#room-title').textContent='Samfunnets hukommelse';}}
$('#exhibit-open').onclick=()=>{if(near)openStory(near);};
function missionsOutcome(id:string){const a=journey.state.attempts[id];return a?.choice!=null?missions.find(m=>m.id===id)!.options[a.choice].protected:null;}
function claimHtml(c:Claim){return `<p class="narrative">${esc(c.text)}</p>`;}
function openStory(id:string){viewOpen=true;pause(true);world?.frameReading(true);$('#near-card').hidden=true;$('#story').hidden=false;document.body.classList.add('reading');if(id==='leader'){current=null;scenario=0;choice=null;renderLeader();}else{current=cases.find(c=>c.id===id)!;step=0;journey.render(current);world?.setOutcome(id,journey.state.attempts[id]?.choice!=null?missionsOutcome(id):null);}$('#story-close').focus();}
function closeStory(){viewOpen=false;world?.frameReading(false);$('#story').hidden=true;document.body.classList.remove('reading');pause(false);nearChanged(near);if(active)$('#world').focus();}
$('#story-close').onclick=()=>{if(guided){guided=false;if(world)world.guided=false;$('#tour-toggle').textContent='Start omvisning';$('#controls-hint').textContent='WASD · Gå     Dra · Se     E · Utforsk';}closeStory();};
const stageNames=['Hva skjedde?','Hva mangler?','Konsekvensen','Hva sa myndigheten?','Lederens perspektiv'];
function renderStory(){if(!current)return;const c=current;$('#story-kicker').textContent=c.wing;const blocks=[c.shortNarrative,c.documentedFacts[0],c.consequence[0],c.authorityFindings[0],null];const block=blocks[step];
 $('#story-content').innerHTML=`<button id="return-mission" class="back-to-mission">← Reparer sporene · Til oppdraget</button><p class="case-meta">${esc(c.organization)} <span>·</span> ${esc(date(c.eventDate))}</p><h2>${esc(c.title)}</h2><p class="case-question">${esc(c.question)}</p><div class="step-dots" aria-label="Fortellingens deler">${stageNames.map((n,i)=>`<button data-step="${i}" class="${i===step?'selected':''}" aria-current="${i===step?'step':'false'}" aria-label="${i+1}. ${n}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div><p class="eyebrow step-title">${String(step+1).padStart(2,'0')} / ${stageNames[step]}</p>${block?claimHtml(block):`<p class="narrative lesson">${esc(c.leadershipLesson)}</p><p class="caption">Museets faglige tolkning.</p>`}${step===1&&c.displayMetric?`<div class="data-emphasis">${esc(c.displayMetric.value)} <span>${esc(c.displayMetric.label)}</span></div>`:''}${step===2&&c.id==='tokke'?'<div class="note">Uavklart lesbarhet er ikke det samme som dokumentert, endelig tap.</div>':''}<p class="evidence-label">${block?`Kilde: ${esc(c.sources[0].institution)} · ${esc(block.locator)}`:'Refleksjon med utgangspunkt i den dokumenterte saken.'}</p><div class="source-actions"><button id="case-sources">Vis kilder ↗</button><button id="case-detail">Fordypning og regelverk</button></div><p class="caption reconstruction">Visuell rekonstruksjon · Gjenstandene er ikke originaldokumenter.</p>`;
 $('#story-nav').innerHTML=`<span>${guided?`OMVISNING ${tourIndex+1} / 6`:'UTFORSK I EGET TEMPO'}</span><button id="story-next" class="primary">${step<4?'Neste del':'Prøv lederoppdraget'} <span>→</span></button>`;
 document.querySelectorAll<HTMLButtonElement>('[data-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);renderStory();world?.setStage(c.id,step);announce(stageNames[step]);});
 $('#return-mission').onclick=()=>journey.render(c,true);$('#case-sources').onclick=()=>sources(c);$('#case-detail').onclick=()=>detail(c);$('#story-next').onclick=()=>{if(step<4){step++;renderStory();world?.setStage(c.id,step);$('#story-next').focus();announce(stageNames[step]);}else journey.render(c,true);};
}
function sourceHtml(s:Source){return `<article class="source"><span class="eyebrow">PRIMÆRKILDE · ${esc(s.institution)}</span><h3>${esc(s.title)}</h3><p>${date(s.date)} · ${esc(s.locator)}</p>${s.excerpt?`<blockquote>«${esc(s.excerpt)}»</blockquote>`:''}<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Åpne originalkilden ↗</a></article>`;}
function sources(c?:MuseumCase){const list=c?[...c.sources,...legalSources.filter(s=>c.currentLegalRelevance.some(x=>x.sourceIds.includes(s.id)))]:[...cases.flatMap(c=>c.sources),...legalSources];showDialog(c?'Kilder · '+c.title:'Kilder og gjeldende regelverk',`<p>Opplysninger kontrollert ${date(c?.sourceCheckedDate??'2026-09-08')}. Kildene åpnes i ny fane.</p>${list.map(sourceHtml).join('')}${c?`<h3>Avgrensninger</h3>${c.disputedOrUncertainClaims.map(t=>`<p class="note">${esc(t)}</p>`).join('')}`:''}`);}
function detail(c:MuseumCase){showDialog('Fordypning · '+c.title,`<p class="eyebrow">${esc(c.location)} · Tilsyn / uttalelse ${date(c.inspectionDate)}</p>${[c.shortNarrative,...c.documentedFacts,...c.consequence,...c.authorityFindings].map(t=>`<p>${esc(t.text)}</p>`).join('')}<h3>Regelverket da</h3>${c.legalFrameworkAtTime.map(t=>`<p>${esc(t.text)}</p>`).join('')}<h3>Regelverket nå · 2026</h3>${c.currentLegalRelevance.map(t=>`<p>${esc(t.text)}</p>`).join('')}<p>Lov om dokumentasjon og arkiv fra 2025 og arkivforskrifta fra 2025 trådte i kraft i hovedsak 1. januar 2026. Eldre paragrafnummer brukes bare om historiske vurderinger.</p><h3>Hva vi ikke kan slutte</h3>${c.disputedOrUncertainClaims.map(t=>`<p class="note">${esc(t)}</p>`).join('')}<p>${esc(c.confidence)}</p><button class="primary" id="detail-sources">Kontroller kildene ↗</button>`);$('#detail-sources').onclick=()=>sources(c);}
function renderLeader(){const s=scenarios[scenario];$('#story-kicker').textContent='V · LEDERENS ROM';$('#story-content').innerHTML=`<button id="leader-plan" class="back-to-mission">Min lederbestilling ↗</button><p class="case-meta">FIRE EKSTRA LEDERVALG</p><h2>Det neste arkivet<br>skapes nå.</h2><p class="case-question">Hvis virksomheten din må forklare denne beslutningen om fem år – finnes sporene?</p><p class="caption">Tenkte lederscenarioer. Mulige følger, ikke historiske hendelser eller sikre utfall.</p><div class="scenario"><span class="eyebrow">VALG ${scenario+1} / 4</span><h3>${s.title}</h3><p>${s.context}</p><div class="choices">${s.choices.map((x,i)=>`<button data-choice="${i}" class="${choice===i?'chosen':''}" aria-pressed="${choice===i}">${x} <span>↗</span></button>`).join('')}</div>${choice!==null?`<ol class="consequence-chain">${s.effects[choice].map(t=>`<li>${t}</li>`).join('')}</ol><p class="reflection">${s.reflection}</p>`:''}</div>`;
 $('#story-nav').innerHTML=`<button id="leader-law">Regelverk 2026 ↗</button><button id="leader-next" class="primary" ${choice===null?'disabled':''}>${scenario<3?'Neste valg':'Ta med deg spørsmålet'} →</button>`;
 document.querySelectorAll<HTMLButtonElement>('[data-choice]').forEach(b=>b.onclick=()=>{choice=Number(b.dataset.choice);renderLeader();announce('Mulig konsekvens: '+s.effects[choice].join('. '));$('#leader-next').focus();});$('#leader-plan').onclick=()=>journey.plan();$('#leader-law').onclick=()=>sources();$('#leader-next').onclick=()=>{if(scenario<3){scenario++;choice=null;renderLeader();}else journey.plan();};
}
function map(){showDialog('Finn ditt neste rom',`<p>Velg en utstilling for å gå rett dit. Du trenger ikke bruke tastatur eller styre kameraet.</p><div class="room-list">${cases.map((c,i)=>`<button data-room="${c.id}"><span class="room-number">${String(i+1).padStart(2,'0')}</span><span><small>${esc(c.wing)}</small><strong>${esc(c.title)}</strong><small>${esc(c.organization)} · ${journey.completed(c.id)?'✓ Oppdrag løst':'Oppdrag venter'}</small></span><span>↗</span></button>`).join('')}<button data-room="leader"><span class="room-number">06</span><span><small>V · LEDERENS ROM</small><strong>Det neste arkivet skapes nå</strong><small>Fire valg om virksomhetens hukommelse</small></span><span>↗</span></button></div><p class="caption">Rom på begge sider av hovedhallen. Installasjonene er visuelle rekonstruksjoner.</p>`);document.querySelectorAll<HTMLButtonElement>('[data-room]').forEach(b=>b.onclick=()=>{closeDialog();guided=false;if(world)world.guided=false;$('#tour-toggle').textContent='Start omvisning';void navigate(b.dataset.room!,true);});}
$('#map-open').onclick=map;
function goHome(){closeStory();if(!world)return;$('#curtain').classList.add('transition');const old=world.settings.reduced;world.settings.reduced=true;world.home();world.settings.reduced=old;setTimeout(()=>$('#curtain').classList.remove('transition'),200);nearChanged(null);}
$('#home').onclick=()=>{guided=false;if(world)world.guided=false;$('#tour-toggle').textContent='Start omvisning';goHome();};
$('#tour-toggle').onclick=()=>{if(guided){guided=false;if(world)world.guided=false;closeStory();$('#tour-toggle').textContent='Start omvisning';$('#controls-hint').textContent='WASD · Gå     Dra · Se     E · Utforsk';}else{guided=true;if(world)world.guided=true;tourIndex=0;$('#tour-toggle').textContent='Avslutt omvisning';$('#controls-hint').textContent='Omvisning · Ta den tiden du trenger.';void navigate(cases[0].id,true);}};
function audioUpdate(){$('#audio-toggle').textContent=sound.enabled?'Lyd på':'Lyd av';$('#audio-toggle').setAttribute('aria-pressed',String(sound.enabled));$('#sound-caption').hidden=!sound.enabled;}
$('#audio-toggle').onclick=()=>{sound.toggle();setTimeout(audioUpdate,80);};
function menu(){showDialog('En pause i besøket',`<p>Bevegelsen er satt på pause. Fortsett når du vil.</p><div class="settings"><label><span>Redusert bevegelse<small>Umiddelbare forflytninger og rolig lys</small></span><input id="reduced" type="checkbox" ${world?.settings.reduced?'checked':''}></label><label><span>Følsomhet for mus og berøring</span><input id="sensitivity" aria-label="Følsomhet" type="range" min="0.3" max="2" step="0.1" value="${world?.settings.sensitivity??1}"></label><label><span>Lydnivå</span><input id="volume" aria-label="Lydnivå" type="range" min="0" max="0.7" step="0.02" value="${sound.volume}"></label><label><span>Tekststørrelse</span><select id="textsize"><option value="1">Vanlig</option><option value="1.15">Større</option><option value="1.3">Størst</option></select></label><label><span>Bildekvalitet</span><select id="quality"><option value="1">Tilpasset enheten</option><option value="0.75">Lavere · spar strøm</option></select></label></div><p>WASD for å gå, piltaster for å gå og snu. Dra i rommet for å se. Dobbeltklikk låser musepekeren; Escape frigjør den og åpner menyen. Ingen hodevugging.</p><button id="resume" class="primary">Fortsett besøket →</button><p><a href="${import.meta.env.BASE_URL}tekst.html">Hele museet som tekst ↗</a> <button id="menu-sources">Alle kilder</button></p>`);
 const save=()=>{try{localStorage.setItem('arkivmuseet-preferences',JSON.stringify({reduced:world?.settings.reduced,sensitivity:world?.settings.sensitivity,textsize:document.documentElement.style.getPropertyValue('--text-scale')||'1',volume:sound.volume,quality:world?.settings.quality}));}catch{}};
 $('#reduced').onchange=()=>{if(world)world.settings.reduced=($('#reduced') as HTMLInputElement).checked;save();};$('#sensitivity').oninput=()=>{if(world)world.settings.sensitivity=Number(($('#sensitivity') as HTMLInputElement).value);save();};$('#volume').oninput=()=>{sound.setVolume(Number(($('#volume') as HTMLInputElement).value));save();};($('#textsize') as HTMLSelectElement).value=document.documentElement.style.getPropertyValue('--text-scale')||'1';$('#textsize').onchange=()=>{document.documentElement.style.setProperty('--text-scale',($('#textsize') as HTMLSelectElement).value);save();};($('#quality') as HTMLSelectElement).value=String(world?.settings.quality??1);$('#quality').onchange=()=>{if(world){world.settings.quality=Number(($('#quality') as HTMLSelectElement).value);world.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6)*world.settings.quality);world.renderer.shadowMap.enabled=world.settings.quality===1;}save();};$('#resume').onclick=closeDialog;$('#menu-sources').onclick=()=>sources();}
$('#menu-open').onclick=menu;
window.addEventListener('keydown',e=>{if(e.code==='Escape'&&active&&!($('#dialog') as HTMLDialogElement).open){e.preventDefault();menu();}});
document.querySelectorAll<HTMLButtonElement>('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);world?.keys.add(b.dataset.key!);});for(const n of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(n,()=>world?.keys.delete(b.dataset.key!));});
document.addEventListener('visibilitychange',()=>{sound.pause(document.hidden||viewOpen||($('#dialog') as HTMLDialogElement).open);});
document.addEventListener('museum-render-error',()=>{showDialog('3D-visningen ble avbrutt',`<p>Nettleseren mistet tilgangen til grafikken. Historiene og kildene er fortsatt tilgjengelige.</p><button id="recover-flat" class="primary">Fortsett reisen uten 3D →</button><p><a href="${import.meta.env.BASE_URL}tekst.html">Åpne tekstversjonen</a></p><p><a href="${import.meta.env.BASE_URL}">Last museet på nytt</a></p>`);$('#recover-flat').onclick=()=>{closeDialog();begin(true,true);};});
async function initialize(){try{const {MuseumWorld}=await import('./world');world=new MuseumWorld($('#world'),cases,{near:nearChanged,activate:openStory,step:()=>sound.step(),menu});try{const p=JSON.parse(localStorage.getItem('arkivmuseet-preferences')||'{}');if(typeof p.reduced==='boolean')world.settings.reduced=p.reduced;if(Number.isFinite(p.sensitivity))world.settings.sensitivity=Math.max(.3,Math.min(2,p.sensitivity));if(['1','1.15','1.3'].includes(p.textsize))document.documentElement.style.setProperty('--text-scale',p.textsize);if(Number.isFinite(p.volume))sound.volume=Math.max(0,Math.min(.7,p.volume));if(p.quality===.75){world.settings.quality=.75;world.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6)*.75);world.renderer.shadowMap.enabled=false;}}catch{}
 await world.init();if(flatMode)world.setPaused(true);($('#enter') as HTMLButtonElement).disabled=false;($('#guided') as HTMLButtonElement).disabled=false;$('#loading').innerHTML='<span class="ready-dot"></span> Museet er åpent · Besøk i ditt eget tempo';
 Object.defineProperty(window,'museumDiagnostics',{value:()=>world?.diagnostics(),writable:false});
 }catch(e){console.error(e);$('#loading').innerHTML=`3D-visningen kunne ikke åpnes. Velg «Spill uten 3D» ovenfor, eller <a href="${import.meta.env.BASE_URL}tekst.html">Les hele utstillingen som tekst ↗</a>`;}}
void initialize();
