import {chromium,devices} from '@playwright/test';
import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const url=process.env.MUSEUM_URL||'http://127.0.0.1:4196/Rolfs-projects-2026/arkivmuseet/';
const out=process.env.MUSEUM_QA_DIR||'qa-output';await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.MUSEUM_CHROME||undefined,headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const log=[],errors=[],badResponses=[];const check=(x,s)=>{assert.ok(x,s);log.push(s);};
const page=await browser.newPage({viewport:{width:1440,height:960}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.url().startsWith(url)&&r.status()>=400)badResponses.push([r.status(),r.url()]);});
async function enterRoom(page,id){
 await page.locator('#map-open').click();
 const room=page.locator(`[data-room="${id}"]`),title=await room.locator('strong').innerText();
 await room.click();
 await page.waitForFunction(title=>document.querySelector('#near-title').textContent===title,title);
 check(await page.locator('#story').isHidden(),id+': room arrival leaves the museum visible');
 await page.locator('#exhibit-open').click();
}
try{
 await page.goto(url);await page.waitForFunction(()=>!document.querySelector('#enter').disabled,null,{timeout:30000});check((await page.evaluate(()=>window.museumDiagnostics().triangles))>30000,'Real WebGL geometry renders');await page.screenshot({path:out+'/final-entrance.png'});
 await page.locator('#enter').click();await page.waitForTimeout(3100);let d=await page.evaluate(()=>window.museumDiagnostics());check(await page.locator('#story').isHidden(),'Entry leaves reading closed');check((await page.locator('#room-kicker').innerText())==='HOVEDHALLEN','Entry begins in the main hall');check(Math.abs(d.position[0])<.1&&d.position[2]>0&&d.position[2]<3,'Entry camera is inside the main hall');await page.keyboard.down('KeyW');await page.waitForTimeout(700);await page.keyboard.up('KeyW');let d2=await page.evaluate(()=>window.museumDiagnostics());check(d2.position[2]>d.position[2]+1,'WASD moves through the hall');
 await page.mouse.move(400,400);await page.mouse.down();await page.mouse.move(540,420);await page.mouse.up();check((await page.evaluate(()=>window.museumDiagnostics().yaw))!==d2.yaw,'Drag-to-look rotates the camera');
 await page.keyboard.press('Escape');check(await page.locator('#dialog').isVisible(),'Escape opens pause menu');const before=await page.evaluate(()=>window.museumDiagnostics().position);await page.keyboard.down('KeyW');await page.waitForTimeout(250);await page.keyboard.up('KeyW');assert.deepEqual(await page.evaluate(()=>window.museumDiagnostics().position),before);log.push('Pause prevents movement');await page.locator('#reduced').check();await page.locator('#textsize').selectOption('1.3');await page.locator('#quality').selectOption('0.75');await page.locator('#resume').click();
 await page.locator('#home').click();await page.waitForTimeout(250);await page.screenshot({path:out+'/final-hall.png'});
 // Collision with centre plinth: walk longer than the distance to it, stay on the entry side.
 await page.locator('#world').focus();await page.keyboard.down('KeyW');await page.waitForTimeout(8000);await page.keyboard.up('KeyW');d=await page.evaluate(()=>window.museumDiagnostics());check(d.position[2]<19&&d.position[2]>17,'Centre plinth blocks passage without trapping the visitor');
 await page.locator('#menu-open').click();await page.locator('#textsize').selectOption('1');await page.locator('#quality').selectOption('1');await page.locator('#resume').click();
 for(const id of ['osen','tokke','innsyn','hanekleiv','npe']){
  await enterRoom(page,id);await page.locator('#mission-read').click();await page.locator('#case-sources').waitFor();check(await page.locator('#story h2').isVisible(),id+': story opens');
  await page.locator('#case-sources').click();const links=await page.locator('#dialog-body .source a').evaluateAll(a=>a.map(x=>({href:x.href,target:x.target,rel:x.rel})));check(links.length>=2&&links.every(l=>l.href.startsWith('https:')&&l.target==='_blank'&&l.rel.includes('noopener')),id+': primary source and current law open safely in new tabs');
  await page.locator('#dialog-close').click();await page.locator('#case-detail').click();check((await page.locator('#dialog-body').innerText()).includes('Regelverket nå'),id+': historical and current law visible');await page.locator('#dialog-close').click();
  for(let i=0;i<4;i++)await page.locator('#story-next').click();check((await page.locator('#story-content').innerText()).includes('Museets faglige tolkning'),id+': all five narrative parts work');await page.screenshot({path:out+'/final-'+id+'.png'});await page.locator('#story-next').click();
 }
 await enterRoom(page,'leader');
 for(let i=0;i<4;i++){await page.locator('[data-choice="0"]').click();check(await page.locator('.consequence-chain li').count()===3,'Leader choice '+(i+1)+': first consequence chain');await page.locator('[data-choice="1"]').click();check(await page.locator('.consequence-chain li').count()===3,'Leader choice '+(i+1)+': alternative consequence chain');if(i===3)await page.screenshot({path:out+'/final-leader.png'});await page.locator('#leader-next').click();}
 check(await page.locator('#action-plan').isVisible(),'Leader room reaches actionable order');await page.locator('#dialog-close').click();await page.locator('#story-close').click();check(await page.locator('#story').isHidden(),'Closing restores free exploration');
 await page.locator('#audio-toggle').click();await page.waitForTimeout(150);check((await page.locator('#audio-toggle').getAttribute('aria-pressed'))==='true','Audio starts only after an explicit gesture');await page.locator('#audio-toggle').click();
 const desktop=await page.evaluate(()=>window.museumDiagnostics());
 const mobile=await browser.newPage({...devices['Pixel 7'],viewport:{width:390,height:844}});mobile.on('pageerror',e=>errors.push('mobile: '+e.message));await mobile.goto(url);await mobile.waitForFunction(()=>!document.querySelector('#enter').disabled);await mobile.screenshot({path:out+'/mobile-entrance.png'});check(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile entrance has no horizontal overflow');await mobile.locator('#enter').tap();await mobile.waitForTimeout(3000);
 const pos=await mobile.evaluate(()=>window.museumDiagnostics().position);const control=await mobile.locator('[data-key="KeyW"]').boundingBox();const cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:control.x+control.width/2,y:control.y+control.height/2}]});await mobile.waitForTimeout(500);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check((await mobile.evaluate(()=>window.museumDiagnostics().position[2]))>pos[2]+.5,'Mobile movement buttons work');
 await enterRoom(mobile,'hanekleiv');await mobile.locator('#mission-read').tap();await mobile.locator('#case-sources').waitFor();await mobile.screenshot({path:out+'/mobile-story.png'});await mobile.locator('#case-sources').tap();await mobile.screenshot({path:out+'/mobile-sources.png'});check(await mobile.locator('#dialog').isVisible(),'Mobile sources are accessible');await mobile.locator('#dialog-close').tap();await mobile.locator('#story-close').tap();await mobile.locator('#menu-open').tap();await mobile.locator('#textsize').selectOption('1.3');await mobile.screenshot({path:out+'/mobile-menu-large.png'});check(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Larger text has no horizontal overflow');
 const mobileStats=await mobile.evaluate(()=>window.museumDiagnostics());await mobile.close();
 const txt=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await txt.goto(url+'tekst.html');check(await txt.locator('article').count()===5,'All five complete stories available without JavaScript');check(await txt.locator('#leder details').count()===8,'All leader alternatives available without JavaScript');check(await txt.locator('a[target="_blank"]').count()>20,'Text version preserves detailed source links');await txt.close();
 check(errors.length===0,'No JavaScript or console errors');check(badResponses.length===0,'No missing application assets');await writeFile(out+'/results.json',JSON.stringify({url,checked:new Date().toISOString(),log,errors,badResponses,desktop,mobile:mobileStats},null,2));console.log(JSON.stringify({passed:log.length,errors,badResponses,desktop,mobile:mobileStats}));
}finally{await browser.close();}
