export const BUILD_INFO = Object.freeze({
  title: "Noark 5-arkivassistent",
  version: "1.0.0",
  corpusVersion: "2026-09-02",
  standardVersion: "Noark 5 versjon 6.0",
  legalBasis: "Arkivregelverket fra 1. januar 2026",
});

export const SOURCES = Object.freeze([
  {
    id: "noark-v6",
    title: "Noark 5 – norsk arkivstandard, versjon 6.0",
    shortTitle: "Noark 5 v6.0",
    publisher: "Nasjonalarkivet",
    published: "24.09.2025",
    type: "Standard",
    url: "https://www.nasjonalarkivet.no/content/uploads/2025/10/Noark-5-versjon-6.pdf",
    note: "Hovedstandarden med konseptuell modell og funksjonelle krav.",
  },
  {
    id: "metadata-v6",
    title: "Noark 5 v6.0 – vedlegg 1: Metadatakatalog",
    shortTitle: "Metadatakatalog v6.0",
    publisher: "Nasjonalarkivet",
    published: "24.09.2025",
    type: "Standardvedlegg",
    url: "https://www.nasjonalarkivet.no/content/uploads/2025/10/Noark-5-versjon-6-vedlegg-1-Metadatakatalog.pdf",
    note: "Definerer metadataelementene og betingelsene for bruk.",
  },
  {
    id: "objects-v6",
    title: "Noark 5 v6.0 – vedlegg 2: Metadata gruppert på objekter",
    shortTitle: "Objektmodell v6.0",
    publisher: "Nasjonalarkivet",
    published: "24.09.2025",
    type: "Standardvedlegg",
    url: "https://www.nasjonalarkivet.no/content/uploads/2025/10/Noark-5-versjon-6-vedlegg-2-Metadata-gruppert-pa-objekter.pdf",
    note: "Logisk modell med objekter, relasjoner og obligatoriske eller valgfrie metadata.",
  },
  {
    id: "noark-page",
    title: "Noark",
    shortTitle: "Noark – temaside",
    publisher: "Nasjonalarkivet",
    published: "Løpende oppdatert",
    type: "Offisiell veiledning",
    url: "https://www.nasjonalarkivet.no/offentlig-forvaltning/regelverk-og-standarder/noark/",
    note: "Status, formål og forholdet mellom Noark og regelverket fra 2026.",
  },
  {
    id: "noark-now",
    title: "Noark – hva nå?",
    shortTitle: "Noark – hva nå?",
    publisher: "Nasjonalarkivet",
    published: "2026",
    type: "Offisiell veiledning",
    url: "https://www.nasjonalarkivet.no/offentlig-forvaltning/regelverk-og-standarder/noark/noark-hva-na/",
    note: "Spørsmål og svar om frivillig bruk av Noark etter regelendringen.",
  },
  {
    id: "systems-guidance",
    title: "Informasjonssystemer: nytt regelverk gir nye muligheter",
    shortTitle: "Krav til informasjonssystemer",
    publisher: "Nasjonalarkivet",
    published: "2026",
    type: "Offisiell veiledning",
    url: "https://www.nasjonalarkivet.no/offentlig-forvaltning/dokumentasjonsforvaltning/informasjonssystemer-nytt-regelverk-gir-nye-muligheter/",
    note: "Praktisk forklaring av funksjonskravene i arkivforskrifta § 5.",
  },
  {
    id: "new-rules",
    title: "Nytt arkivregelverk",
    shortTitle: "Nytt arkivregelverk",
    publisher: "Nasjonalarkivet",
    published: "2026",
    type: "Offisiell oversikt",
    url: "https://www.nasjonalarkivet.no/offentlig-forvaltning/det-nye-arkivregelverket/",
    note: "Samleside for arkivlova, arkivforskrifta og bevaringsforskrifta.",
  },
  {
    id: "archive-law",
    title: "Lov om dokumentasjon og arkiv (arkivlova)",
    shortTitle: "Arkivlova",
    publisher: "Lovdata",
    published: "20.06.2025",
    type: "Lov",
    url: "https://lovdata.no/dokument/NL/lov/2025-06-20-96",
    note: "Gjeldende arkivlov fra 1. januar 2026.",
  },
  {
    id: "archive-regulation",
    title: "Forskrift om dokumentasjon og arkiv (arkivforskrifta)",
    shortTitle: "Arkivforskrifta",
    publisher: "Lovdata",
    published: "17.12.2025",
    type: "Forskrift",
    url: "https://lovdata.no/dokument/SF/forskrift/2025-12-17-2647",
    note: "Gjeldende forskrift, blant annet §§ 5–7, § 15 og § 28.",
  },
  {
    id: "preservation-regulation",
    title: "Forskrift om kva dokumentasjon som skal takast vare på for ettertida",
    shortTitle: "Bevaringsforskrifta",
    publisher: "Lovdata",
    published: "19.12.2025",
    type: "Forskrift",
    url: "https://lovdata.no/dokument/SF/forskrift/2025-12-19-2729",
    note: "Regler om hvilken dokumentasjon som skal bevares for ettertiden.",
  },
]);

const sourceIds = new Set(SOURCES.map((source) => source.id));

export function record({
  id,
  source,
  title,
  section,
  page = null,
  requirement = null,
  requirementType = null,
  topic,
  tags = [],
  summary,
  detail,
}) {
  if (!sourceIds.has(source)) throw new Error(`Ukjent kilde: ${source}`);
  return Object.freeze({
    id,
    source,
    title,
    section,
    page,
    requirement,
    requirementType,
    topic,
    tags: Object.freeze(tags),
    summary,
    detail,
  });
}
