// Verified against the linked official pages on 2026-09-07.
// Guidance is paraphrased; format rows are factual catalogue data.
// User questions and analytics must NEVER be added to this public source file.
export const GUIDANCE_VERIFIED_AT = '2026-09-07';
export const GUIDANCE_SOURCES = Object.freeze([
  { id: 'na-formats', title: 'Aksepterte filformater for avlevering til Nasjonalarkivet', shortTitle: 'Aksepterte avleveringsformater', publisher: 'Nasjonalarkivet', published: 'Publiseringsdato ikke fastsatt her', type: 'Offisiell veiledning', url: 'https://www.nasjonalarkivet.no/offentlig-forvaltning/dokumentasjonsforvaltning/anbefalte-filformater-for-avlevering-til-nasjonalarkivet/', note: 'Gjeldende formatliste med filendelser, PRONOM-identifikatorer og versjoner. Ikke en generell regel for alle arkivdepot eller alle faser av arkivdanningen.', scope: 'Avlevering til Nasjonalarkivet', verifiedAt: GUIDANCE_VERIFIED_AT, status: 'current-guidance' },
  { id: 'na-internal-control', title: 'Etablere internkontroll med dokumentasjonsforvaltningen', shortTitle: 'Internkontroll', publisher: 'Nasjonalarkivet', published: 'Publiseringsdato ikke fastsatt her', type: 'Offisiell veiledning', url: 'https://www.nasjonalarkivet.no/veiledere/etablere-internkontroll-med-dokumentasjonsforvaltningen/', note: 'Praktiske steg for ansvar, risiko, dokumentfangst, avvik, ressurser og kontroll.', scope: 'Virksomheter underlagt arkivloven', verifiedAt: GUIDANCE_VERIFIED_AT, status: 'current-guidance' },
  { id: 'na-appraisal', title: 'Veileder for å vurdere hvilken dokumentasjon som skal forvaltes som arkiv', shortTitle: 'Dokumentasjonskartlegging', publisher: 'Nasjonalarkivet', published: 'Publiseringsdato ikke fastsatt her', type: 'Offisiell veiledning', url: 'https://www.nasjonalarkivet.no/veiledere/veileder-for-a-vurdere-hvilken-dokumentasjon-som-skal-forvaltes-som-arkiv/', note: 'Systemkartlegging og funksjons- og prosessanalyse. Arkivplikt er ikke det samme som bevaring for ettertiden.', scope: 'Virksomheter underlagt arkivloven', verifiedAt: GUIDANCE_VERIFIED_AT, status: 'current-guidance' },
  { id: 'na-preservation', title: 'Veileder om bevaringskriteriene i § 2 i arkivforskriften', shortTitle: 'Bevaringskriterier', publisher: 'Nasjonalarkivet', published: 'Publiseringsdato ikke fastsatt her', type: 'Offisiell veiledning', url: 'https://www.nasjonalarkivet.no/veiledere/veileder-om-bevaringskriteriene-i-%C2%A7-2-i-arkivforskriften/', note: 'Kriterier for bevaringsvurdering; veiledningen erstatter ikke et bevarings- eller kassasjonsvedtak.', scope: 'Statlige organers forslag om bevaring og kassasjon', verifiedAt: GUIDANCE_VERIFIED_AT, status: 'current-guidance' },
  { id: 'na-paper-conversion', title: 'Veileder for konvertering av papirarkiver', shortTitle: 'Konvertering av papirarkiver', publisher: 'Nasjonalarkivet', published: 'Publiseringsdato ikke fastsatt her', type: 'Offisiell veiledning', url: 'https://www.nasjonalarkivet.no/veiledere/veileder-for-konvertering-av-papirarkiver/', note: 'Kvalitetskontroll, metadata, overføring og vilkår for destruksjon. Kommuner må avklare med sitt depot.', scope: 'Primært avsluttede statlige papirarkiver', verifiedAt: GUIDANCE_VERIFIED_AT, status: 'current-guidance' },
  { id: 'na-single-disposal', title: 'Veileder for virksomheter som mottar søknad om kassasjon av enkeltopplysninger', shortTitle: 'Kassasjon av enkeltopplysninger', publisher: 'Nasjonalarkivet', published: 'Publiseringsdato ikke fastsatt her', type: 'Offisiell veiledning', url: 'https://www.nasjonalarkivet.no/veiledere/veileder-for-virksomheter-som-mottar-soknad-om-kassasjon-av-enkeltopplysninger/', note: 'Skiller personvernrettslig sletting fra kassasjon av enkeltopplysninger i særlige tilfeller.', scope: 'Virksomheter underlagt arkivloven', verifiedAt: GUIDANCE_VERIFIED_AT, status: 'current-guidance' },
  { id: 'arkade-manual', title: 'Arkade 5 – brukerveiledning', shortTitle: 'Arkade 5 – brukerveiledning', publisher: 'Nasjonalarkivet', published: 'Publiseringsdato ikke fastsatt her', type: 'Verktøydokumentasjon', url: 'https://docs.arkade.arkivverket.no/no/latest/Brukerveiledning.html', note: 'Verktøydokumentasjon. Enkelte formatkontroller omtaler fortsatt eldre forskrift; bruk Nasjonalarkivets aktuelle formatliste for akseptvilkår.', scope: 'Teknisk testing og pakking, ikke selvstendig rettsgrunnlag', verifiedAt: GUIDANCE_VERIFIED_AT, status: 'tool-documentation' },
].map(Object.freeze));
const guidance = (r) => Object.freeze({ page: null, requirement: null, requirementType: null, verifiedAt: GUIDANCE_VERIFIED_AT, ...r, tags: Object.freeze(r.tags) });
export const GUIDANCE_RECORDS = Object.freeze([
  { id: 'guide-format-agreement', source: 'na-formats', title: 'Avleveringsformater: avtale og originalfiler', section: 'Innledning – avtale og originalfiler', topic: 'Format', tags: ['avlevering', 'avlevere', 'filformater', 'formater', 'aksepterte', 'godkjente', 'deponering', '§ 21 e', 'originalformat'], summary: 'Formatvalg ved avlevering til Nasjonalarkivet avklares etter arkivforskrifta § 21 e. Originalfiler på den aksepterte listen trenger ikke særskilt formatavtale.', detail: 'Formataksept alene dokumenterer ikke at hele leveransen er godkjent. Listen gjelder Nasjonalarkivet; avklar andre depot sine krav separat.' },
  { id: 'guide-format-conversion', source: 'na-formats', title: 'Konvertering uten informasjonstap', section: 'Innledning – konvertering', topic: 'Format', tags: ['konvertering', 'konvertere', 'PDF/A', 'DOCX', 'XLSX', 'regneark', 'formler', 'originalfiler', 'informasjonstap'], summary: 'Nasjonalarkivet foretrekker et akseptert format når originalen kan konverteres uten informasjonstap.', detail: 'Vurder informasjonen som skal bevares; PDF/A er ikke det eneste formatet på den aktuelle avleveringslisten.' },
  { id: 'guide-format-unlisted', source: 'na-formats', title: 'Format som ikke står på listen', section: 'Innledning og formatlisten – avgrensning', topic: 'Format', tags: ['DWG', 'HEIC', 'WebP', 'PST', 'EML', 'ZIP', 'PDF/A-4', 'PDF 2.0', 'ikke listet', 'avtale'], summary: 'Fravær fra formatlisten er ikke et dokumentert generelt forbud. Be Nasjonalarkivet avklare formatet for den konkrete avleveringen.', detail: 'Ikke utled aksept for en ukjent variant fra filendelsen alene. Dette er en forsiktig avgrensning av hva listen dokumenterer.' },
  { id: 'guide-control-steps', source: 'na-internal-control', title: 'Etabler internkontroll og dokumentasjonsplan', section: 'Seks steg for å etablere internkontroll', topic: 'Internkontroll', tags: ['internkontroll', 'dokumentasjonsplan', 'arkivplan', 'ansvar', 'ledelse', 'seks steg'], summary: 'Forankre internkontrollen i ledelsen: kartlegg krav og mål, fordel ansvar, vurder risiko, håndter avvik, sikre kompetanse og gjennomfør kontroll.', detail: 'Dokumentasjonsplanen skal støtte internkontrollen; virksomheten kan tilpasse utformingen og bruke eksisterende kvalitetssystem.' },
  { id: 'guide-control-capture', source: 'na-internal-control', title: 'Dokumentfangst fra Teams, SharePoint, SMS og e-post', section: 'Steg 3 – Dokumentfangst', topic: 'Dokumentfangst', tags: ['Teams', 'SharePoint', 'SMS', 'chat', 'e-post', 'samhandling', 'dokumentfangst'], summary: 'Internkontrollveilederen anbefaler å undersøke dokumentfangst fra samhandlingsløsninger, telefon, SMS og e-post.', detail: 'Kartlegg informasjonsflyt og ansattes rutiner. Veilederen innebærer ikke at alle meldinger automatisk skal arkiveres.' },
  { id: 'guide-control-risk', source: 'na-internal-control', title: 'Risikobasert kontroll og avvikshåndtering', section: 'Steg 3–6 – risiko, avvik og kontroll', topic: 'Internkontroll', tags: ['risikovurdering', 'sannsynlighet', 'konsekvens', 'avvik', 'kontroll', 'tiltak'], summary: 'Vurder sannsynlighet og konsekvens for dokumentasjonsforvaltningen, og tilpass tiltakene til risikoen.', detail: 'Dokumenter kontrollaktiviteter, avvik og oppfølging med tydelig ansvar og beslutningsvei.' },
  { id: 'guide-appraisal-systems', source: 'na-appraisal', title: 'Kartlegg alle systemer, ikke bare arkivsystemet', section: 'Systemkartlegging', topic: 'Dokumentasjonsplan', tags: ['systemkartlegging', 'fagsystem', 'HR', 'økonomi', 'register', 'samhandling', 'systemoversikt'], summary: 'Systemoversikten bør omfatte fagsystemer, registre, HR/økonomi, samhandlingsverktøy, e-post og eventuelle analoge systemer.', detail: 'Dokumenter hva systemene brukes til, hvilken dokumentasjon de inneholder, datastruktur og formater; kvalitetssikre med prosessansvarlige.' },
  { id: 'guide-appraisal-process', source: 'na-appraisal', title: 'Funksjons- og prosessanalyse', section: 'Funksjons- og prosessanalyse', topic: 'Dokumentasjonsplan', tags: ['funksjonsanalyse', 'prosessanalyse', 'kartlegging', 'mandat', 'aktivitet', 'arkivplikt'], summary: 'Koble systemkartlegging til virksomhetens funksjoner, prosesser og aktiviteter for å finne hvilken dokumentasjon som skapes.', detail: 'Vurder deretter arkivplikt etter § 1. Kartleggingen er også grunnlag for senere bevaringsvurdering, ikke et kassasjonsvedtak.' },
  { id: 'guide-appraisal-update', source: 'na-appraisal', title: 'Når bør dokumentasjonskartleggingen oppdateres?', section: 'Kort fortalt', topic: 'Dokumentasjonsplan', tags: ['anskaffelse', 'omorganisering', 'nye oppgaver', 'endring', 'revisjon'], summary: 'Oppdater kartleggingen ved revisjon av dokumentasjonsplanen, endrede arbeidsprosesser, nye systemer, nye oppgaver og omorganisering.', detail: 'Dokumenter vurderingene og hvor dokumentasjonen skal forvaltes som arkiv.' },
  { id: 'guide-preservation-criteria', source: 'na-preservation', title: 'Fem kriterier for bevaring for ettertiden', section: 'Hvordan bruke veilederen? og kriteriene 1–5', topic: 'Bevaring og kassasjon', tags: ['bevaringskriterier', 'bevaringsvurdering', '§ 2', 'bevaring', 'statlig', 'fagsaker'], summary: 'Vurder samfunnsendringer, natur og klima, offentlig oppgaveforvaltning, oppgaver hos andre omfattede rettssubjekter og framtidig rettighetsdokumentasjon.', detail: 'For statlige fagsaker støtter kriteriene forslag etter bevaringsforskrifta § 18. Ett kriterium kan være nok for å foreslå bevaring; vurder alle relevante ved tvil.' },
  { id: 'guide-preservation-authority', source: 'na-preservation', title: 'Bevaringsvurdering er ikke tillatelse til kassasjon', section: 'Innledning og målgruppe', topic: 'Bevaring og kassasjon', tags: ['kassasjon', 'kassere', 'tillatelse', 'bevaringsvedtak', 'egenforvaltning', 'bevaringstid'], summary: 'Kassasjon krever hjemmel i annen lov eller tillatelse fra Nasjonalarkivet. En egen vurdering alene er ikke tilstrekkelig.', detail: 'Veilederen gjelder særlig statlige forslag på fagområder; egenforvaltningssaker har egne bestemmelser i bevaringsforskrifta kapittel 2.' },
  { id: 'guide-paper-quality', source: 'na-paper-conversion', title: 'Skanning: kvalitetskontroll og metadata', section: 'Krav til kvalitetssikring; Metadata og detaljnivå', topic: 'Mediekonvertering', tags: ['skanning', 'mediekonvertering', 'kvalitetskontroll', 'metadata', 'papirarkiv'], summary: 'Dokumenter kvalitetskontroll av konverteringen og kontroller at metadata er riktig knyttet til de skannede dokumentene.', detail: 'Bevar opplysninger om arkivskaper og opprinnelig struktur. Avklar formater og metadata med mottakende depot.' },
  { id: 'guide-paper-destruction', source: 'na-paper-conversion', title: 'Kan papiroriginalene destrueres etter skanning?', section: 'Vilkår for destruksjon etter skanning', topic: 'Mediekonvertering', tags: ['destruksjon', 'destruere', 'makulere', 'papiroriginal', 'skanning', 'godkjenning'], summary: 'Ved avlevering til Nasjonalarkivet må konverteringen være godkjent før papiroriginalene destrueres.', detail: 'Vurder også særskilte juridiske bevaringshensyn og destruksjonsforbud etter § 19. En skannet kopi alene er ikke tilstrekkelig.' },
  { id: 'guide-paper-municipal', source: 'na-paper-conversion', title: 'Kommunal mediekonvertering: avklar med IKA eller depot', section: 'Målgruppe', topic: 'Mediekonvertering', tags: ['kommune', 'kommunal', 'fylkeskommune', 'IKA', 'arkivdepot', 'mediekonvertering'], summary: 'Kommuner og fylkeskommuner bør avklare med sitt IKA eller arkivdepot om mediekonvertering er aktuelt.', detail: 'Veilederen er primært skrevet for avsluttede statlige papirarkiver som skal overføres til Nasjonalarkivet.' },
  { id: 'guide-single-distinction', source: 'na-single-disposal', title: 'Sletting etter personvernregler og kassasjon av enkeltopplysninger', section: 'Forskjellen mellom sletting og kassasjon', topic: 'Bevaring og kassasjon', tags: ['GDPR', 'sletting', 'enkeltopplysninger', 'personopplysninger', '§ 13', 'kassasjon'], summary: 'Skill mellom sletting etter annet regelverk og kassasjon av enkeltopplysninger etter arkivlova § 13.', detail: 'Nasjonalarkivet behandler kassasjonssøknader i særlige tilfeller, ikke generelle søknader om personvernrettslig sletting.' },
  { id: 'guide-single-process', source: 'na-single-disposal', title: 'Forbered en søknad om kassasjon av enkeltopplysninger', section: 'Forundersøkelse av kassasjonssøknad', topic: 'Bevaring og kassasjon', tags: ['kassasjonssøknad', 'søknad', 'enkeltopplysning', 'innstilling', 'behandlingsformål'], summary: 'Avklar hvilke opplysninger saken gjelder, behandlingsformål, plasseringer i arkivet, bevaringsregler og praktisk kassasjonsmetode.', detail: 'Virksomheten sender en begrunnet innstilling. Terskelen er høy, og vurderingen må omfatte alle relevante kriterier.' },
  { id: 'guide-arkade-analysis', source: 'arkade-manual', title: 'Arkade: formatidentifikasjon og pakking', section: 'analyse – Utfør analyse; pack – Pakking', topic: 'Uttrekk', tags: ['Arkade', 'PRONOM', 'PUID', 'DROID', 'formatanalyse', 'SIP', 'DIAS', 'pakking'], summary: 'Arkade kan identifisere filformater med PRONOM og produsere formatrapport ved pakking av uttrekk.', detail: 'Identifikasjon, formatvalidering og mottakerens godkjenning er ulike kontroller. Et teknisk treff er ikke alene en godkjent avlevering.' },
  { id: 'guide-arkade-pdfa', source: 'arkade-manual', title: 'Arkade: PDF/A-validering har en dokumentert begrensning', section: 'Validering av arkivformat', topic: 'Uttrekk', tags: ['Arkade', 'PDF/A', 'validering', 'validator', '2.12.5', 'formatkontroll'], summary: 'Den kontrollerte Arkade-veiledningen sier at PDF/A-validering er deaktivert fra 2.12.5 i påvente av en løsning.', detail: 'Sjekk dokumentasjon for faktisk installert versjon. Den eldre PDF/A-listen i verktøydokumentasjonen erstatter ikke Nasjonalarkivets aktuelle avleveringsliste.' },
].map(guidance));
// [stable ID, format, extensions, PRONOM PUIDs, versions explicitly listed]
export const FORMAT_ROWS = Object.freeze([
  ['csv', 'CSV', 'csv', 'x-fmt/18', ''],
  ['json', 'JSON', 'json', 'fmt/817', ''],
  ['geojson', 'GeoJSON', 'geojson json', 'fmt/1367', ''],
  ['jsonld', 'JSON-LD', 'jsonld', 'fmt/880', ''],
  ['xml', 'XML', 'xml', 'fmt/101 fmt/1776', '1.0, 1.1'],
  ['xsd', 'XML Schema Definition', 'xsd', 'x-fmt/280', ''],
  ['sgml', 'SGML', 'sgm sgml', 'x-fmt/195', ''],
  ['sql', 'SQL data', 'sql', 'fmt/206', ''],
  ['siard', 'SIARD', 'siard', 'fmt/161 fmt/995 fmt/1196 fmt/1777', '1.0, 2.0, 2.1, 2.2'],
  ['txt-plain', 'Plain Text', 'txt', 'x-fmt/111', ''],
  ['txt-unicode', 'Unicode Text', 'txt', 'x-fmt/16', ''],
  ['tiff', 'TIFF', 'tif tiff', 'fmt/353', '6'],
  ['tiff-fx', 'TIFF-FX', 'tif tiff', 'fmt/156', ''],
  ['geotiff', 'GeoTIFF', 'tif tiff', 'fmt/155', '6'],
  ['tiff-it', 'TIFF/IT', 'tif tiff', 'fmt/153', ''],
  ['pdf', 'PDF', 'pdf', 'fmt/14 fmt/15 fmt/16 fmt/17 fmt/18 fmt/19 fmt/20 fmt/276', '1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7'],
  ['pdfa-1a', 'PDF/A-1a', 'pdf', 'fmt/95', '1a'],
  ['pdfa-1b', 'PDF/A-1b', 'pdf', 'fmt/354', '1b'],
  ['pdfa-2a', 'PDF/A-2a', 'pdf', 'fmt/476', '2a'],
  ['pdfa-2b', 'PDF/A-2b', 'pdf', 'fmt/477', '2b'],
  ['pdfa-2u', 'PDF/A-2u', 'pdf', 'fmt/478', '2u'],
  ['pdfa-3a', 'PDF/A-3a', 'pdf', 'fmt/479', '3a'],
  ['pdfa-3b', 'PDF/A-3b', 'pdf', 'fmt/480', '3b'],
  ['pdfa-3u', 'PDF/A-3u', 'pdf', 'fmt/481', '3u'],
  ['jpeg', 'JPEG File Interchange Format', 'jpeg jpe jpg jif jfif jfi', 'fmt/42 fmt/43 fmt/44', '1.00, 1.01, 1.02'],
  ['jpeg-raw', 'Raw JPEG Stream', 'jpeg jpe jpg jif jfif jfi', 'fmt/41', ''],
  ['jp2', 'JPEG 2000 part 1', 'jp2', 'x-fmt/392', ''],
  ['png', 'PNG', 'png', 'fmt/11 fmt/12 fmt/13', '1.0, 1.1, 1.2'],
  ['sosi', 'SOSI', 'sos sosi', 'fmt/1246 fmt/1247 fmt/1248 fmt/1249 fmt/1250', 'uspesifisert, 4.0, 4.1, 4.5, 8.1'],
  ['gml', 'GML', 'gml', 'x-fmt/227 fmt/1047', 'uspesifisert, 3.2'],
  ['mpeg2', 'MPEG-2 Elementary Stream', 'mpg mpeg m2v', 'fmt/640', ''],
  ['mp4', 'MPEG-4 Media File', 'mp4 m4v m4a f4v f4a', 'fmt/199', ''],
  ['mj2', 'Motion JPEG 2000', 'mj2 mjp2', 'fmt/337', ''],
  ['matroska', 'Matroska', 'mkv mk3d mka mks', 'fmt/569', '1, 2, 3, 4'],
  ['mp3', 'MPEG 1/2 Audio Layer 3', 'mp3', 'fmt/134', ''],
  ['wave', 'Waveform Audio', 'wav wave', 'fmt/6 fmt/141 fmt/142', ''],
  ['bwf', 'Broadcast WAVE', 'wav', 'fmt/1 fmt/2 fmt/527 fmt/703 fmt/704 fmt/705', '0, 1, 2'],
  ['flac', 'FLAC', 'flac', 'fmt/279', '1.2.1'],
  ['ogg', 'Ogg FLAC', 'ogg', 'fmt/947', ''],
  ['docx', 'Microsoft Word OOXML', 'docx wbk', 'fmt/412', ''],
  ['docm', 'Word makroaktivert dokument', 'docm', 'fmt/523', ''],
  ['dotx', 'Word mal', 'dotx', 'fmt/597', ''],
  ['dotm', 'Word makroaktivert mal', 'dotm', 'fmt/599', ''],
  ['xlsx', 'Microsoft Excel OOXML', 'xlsx', 'fmt/214', ''],
  ['xlsm', 'Excel makroaktivert regneark', 'xlsm', 'fmt/445', ''],
  ['xltx', 'Excel mal', 'xltx', 'fmt/598', ''],
  ['xltm', 'Excel makroaktivert mal', 'xltm', 'fmt/627', ''],
  ['xlam', 'Excel makroaktivert tillegg', 'xlam', 'fmt/628', ''],
  ['pptx', 'Microsoft PowerPoint OOXML', 'pptx', 'fmt/215', ''],
  ['pptm', 'PowerPoint makroaktivert presentasjon', 'pptm', 'fmt/487', ''],
  ['ppam', 'PowerPoint makroaktivert tillegg', 'ppam', 'fmt/633', ''],
  ['ppsm', 'PowerPoint makroaktivert fremvisning', 'ppsm', 'fmt/630', ''],
  ['sldm', 'PowerPoint makroaktivert lysbilde', 'sldm', 'fmt/636', ''],
  ['potm', 'PowerPoint makroaktivert mal', 'potm', 'fmt/632', ''],
  ['ppsx', 'PowerPoint fremvisning', 'ppsx', 'fmt/629', ''],
  ['potx', 'PowerPoint mal', 'potx', 'fmt/631', ''],
  ['odt', 'OpenDocument Text', 'odt ott', 'fmt/136 fmt/290 fmt/291 fmt/1756', '1.0, 1.1, 1.2, 1.3'],
  ['ods', 'OpenDocument Spreadsheet', 'ods ots', 'fmt/137 fmt/294 fmt/295 fmt/1755', '1.0, 1.1, 1.2, 1.3'],
  ['odp', 'OpenDocument Presentation', 'odp otp', 'fmt/138 fmt/292 fmt/293 fmt/1754', '1.0, 1.1, 1.2, 1.3'],
  ['warc', 'WARC', 'warc', 'fmt/289 fmt/1355 fmt/1281', 'uspesifisert, 1.0, 1.1'],
  ['html', 'HTML', 'htm html', 'fmt/96 fmt/97 fmt/98 fmt/99 fmt/100 fmt/471', 'uspesifisert, 2.0, 3.2, 4.0, 4.01, 5'],
  ['xhtml', 'XHTML', 'htm html', 'fmt/102 fmt/103', '1.0, 1.1'],
  ['ifc', 'Industry Foundation Classes', 'ifc', 'fmt/659 fmt/699 fmt/700', '2x2, 2x3, 4'],
  ['ifcxml', 'Industry Foundation Classes XML', 'ifcXML', 'fmt/663', ''],
  ['tar', 'Tape Archive Format', 'tar', 'x-fmt/265', ''],
].map((r) => Object.freeze(r)));

export const FORMAT_RECORDS = Object.freeze(FORMAT_ROWS.map(([id, name, extensions, puids, versions]) => {
  const family = /^pdfa-([123])/.exec(id);
  return Object.freeze({
    id: `format-${id}`, source: 'na-formats', title: `${name} (${extensions.replaceAll(' ', ', ')}) ved avlevering`,
    section: `Aksepterte filformater ved avlevering – ${name}`, page: null, requirement: null, requirementType: null,
    topic: 'Format', verifiedAt: GUIDANCE_VERIFIED_AT,
    tags: Object.freeze([name, ...extensions.split(' '), ...puids.split(' '),
      'avlevering', 'avlevere', 'akseptert', 'godkjent', 'filformat', ...(family ? [`PDF/A-${family[1]}`] : []),
      ...(/Excel|Spreadsheet/.test(name) ? ['regneark', 'formler'] : []),
      ...(/Word|Text/.test(name) ? ['tekstdokument'] : []),
      ...(/SIARD/.test(name) ? ['database', 'databaser', 'versjon'] : [])]),
    summary: `${name} (${extensions.replaceAll(' ', ', ')}) står på Nasjonalarkivets liste over aksepterte avleveringsformater.`,
    detail: `PRONOM: ${puids.replaceAll(' ', ', ')}. ${versions ? `Oppførte versjoner: ${versions}.` : 'Versjonsfeltet er tomt i kildetabellen; det er ikke en garanti for alle versjoner.'} Se vilkårene for originalfiler, konvertering og avtale i samme kilde.`,
  });
}));
